Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 04:39:16 +0400
X-Deliver-To: lavrushin@iph.ru
Received: from alpha.sferacom.ru ([213.24.91.246] verified)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP-TLS id 187642193 for lavrushin@iph.ru; Mon, 26 May 2003 04:42:03 +0400
Received: from sonya (fw-1.pne.magadan.ru [213.24.242.99])
	by alpha.sferacom.ru (8.11.6/8.11.3) with SMTP id h4Q0fXK00807
	for <lavrushin@iph.ru>; Mon, 26 May 2003 12:41:43 +1200 (MAGST)
	(envelope-from pne@sferacom.ru)
Message-ID: <058101c32328$4368ee00$7600a8c0@sonya>
Reply-To: "Sh. Sonia" <pne@sferacom.ru>
From: "Sh. Sonia" <pne@sferacom.ru>
To: <lavrushin@iph.ru>
References: <000201c32106$ee9b6e70$a4180e0a@iph.int>
Subject: (Archive Copy) Re:
Date: Mon, 26 May 2003 12:43:41 +1100
Organization: PNE
MIME-Version: 1.0
Content-Type: text/plain;
	charset="koi8-r"
Content-Transfer-Encoding: 8bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2919.6700
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2919.6700
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

Андрей,

Ты к нам едешь или нет,,,
Хочу тебе заказать клубники, если можно конечно???

Sonya
Pacific North Equipment (Magadan), Inc.

