Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 03:05:06 +0400
X-Deliver-To: krylova@iph.ru
Received: from mx9.mail.ru ([194.67.23.29] verified)
  by frontend2.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187847542 for krylova@iph.ru; Mon, 26 May 2003 03:08:14 +0400
Received: from mail by mx9.mail.ru with local
	id 19K4ay-000IP2-00
	for krylova@iph.ru; Mon, 26 May 2003 03:08:04 +0400
X-ResentFrom: <landysh_2000@mail.ru>
Received: from [24.165.51.46] (port=3023 helo=24.165.51.46)
	by mx9.mail.ru with smtp
	id 19K4aw-000IHU-00; Mon, 26 May 2003 03:08:03 +0400
From: =?koi8-r?B?9OXu7unz?= <78k3@marss.com>
To: ouzqce <ouzqce@mail.ru>
Subject: (Archive Copy) =?koi8-r?B?8NLFxMzBx8HFzSDPwtXexc7JxSDUxc7OydPVISAgICAgICAgICAgICAgICAgICAgICAgICAgICAg?=
	=?koi8-r?B?ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg?=
	=?koi8-r?B?ICAgICAgICAgICAgINHBx9HH0tDaxSAgICAgzs7cICAgIM7cxc/XziAgwdA=?=
Date: Mon, 26 May 2003 02:29:13 +0400
Reply-To: 78k3@marss.com
Mime-Version: 1.0
Content-Type: text/html; charset="koi8-r"
Message-Id: <E19K4aw-000IHU-00.78k3-marss-com@mx9.mail.ru>
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

<html>
<head>
	<title></title>
</head>
<body>
<table border="2" bordercolor="#993300" cellpadding="4" cellspacing="1" width="600" align=center>
<tr>
<td align="middle" bgcolor="#f3f0ed" width="100%">
<font color="#993300" size="+1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Предлагаем обучение теннису!</b></font>
</td>
</tr>
<tr>
<td align="justify" style="FONT: 12px Verdana, Geneva, Arial, Helvetica, sans-serif">Предлагаем обучение теннису в группах - постановка техники, навыки игры - на кортах в районе <STRONG>Севастопольского проспекта(м.Академическая, м.Профсоюзная, м.Нагорная).</STRONG>Группы формируются по возрасту и уровню подготовки. Возраст обучающихся от 7 лет.<font color="#ffffff">ANYSC  сБПф </font><br><STRONG>СТОИМОСТЬ 1</STRONG>занятия на кортах:<font color="#ffffff">СББЮД JXJYK </font><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<STRONG>2-х</STRONG> часовое занятие в группе из <STRONG>4-х</STRONG> человек - <STRONG>550</STRONG>руб.<br><STRONG>ОПЛАТА</STRONG> производится за <STRONG>1</STRONG> месяц. Стоимость абонемента от 
<STRONG>2200</STRONG> руб.<br>Предлагаем также услуги профессионального стрингера - перетяжка теннисных ракеток.<font color="#ffffff">ГБю  </font><br>Стоимость вместе с нашим комплектом струн - от <STRONG>500</STRONG> руб.<font color="#ffffff">ЩСЙЩю  PAUDY  </font></td></tr><tr><td align="middle" bgcolor="#f3f0ed" width="100%"><STRONG>НЕ ЗАНИМАЕМСЯ ПОДГОТОВКОЙ ПРОФЕССИОНАЛЬНЫХ<br>СПОРТСМЕНОВ И СДАЧЕЙ КОРТОВ В АРЕНДУ!</STRONG>     <br><font color="#993300" size="+1">Тел.: <b>517-86-18</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E-mail: <b><A href="mailto:besttnns@netscape.net">besttnns@netscape.net</A></b></font>
</td>
</tr>
</table>
<br><br>
<br>
<br>
<font color="#ffffff">SBSLJKLKGBG  бмйкй япгяахпйбп     ябечс  юкямпфлйч   EQDNAPABO     чсогбпя ояццщонб   нмъкцйкяр  болддхбяч  </font>
</body>
</html>

