Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 06:52:32 +0400
X-Deliver-To: goncharova@iph.ru
Received: from cat244.subscribe.ru ([81.9.34.244] verified)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187653790 for goncharova@iph.ru; Mon, 26 May 2003 06:54:50 +0400
X-Felis-Deliver-Id: B710519C44E3; Mon, 26 May 2003 06:51:32 +0400
X-Felis-Queue-Id: 20030526065103
Message-Id: <20030526065417_hk_=3405====n==t_@tax.lawlisttop.subscribe>
Precedence: normal
List-Id: <tax.lawlisttop.subscribe.ru>
List-Help: <mailto:ask@subscribe.ru>
List-Owner: <mailto:ask@subscribe.ru>
List-Subscribe: <http://Subscribe.Ru/catalog/tax.lawlisttop>
List-Unsubscribe: <http://Subscribe.Ru/catalog/tax.lawlisttop>
List-Archive:  <http://Subscribe.Ru/archive/tax.lawlisttop>
List-Post: NO
Date: Mon, 26 May 2003 06:54:04 +0400
From: Subscribe.Ru <namma397137@subscribe.ru>
To: "tax.lawlisttop" <goncharova@iph.ru> (397137)
Subject: (Archive Copy) =?koi8-r?Q?=EB=CC=C5=D2=CB.=F2=D5:=20?=
 =?koi8-r?Q?=F0=D2=C1=CB=D4=C9=DE=C5=D3=CB=C1=D1=20=D0=CF=CD=CF=DD=D8=20?=
 =?koi8-r?Q?=C2=D5=C8=C7=C1=CC=D4=C5=D2=D5?=
MIME-Version: 1.0
Content-Type: multipart/related;
  boundary="=felis-related=20030526065413=7019";
  type=text/html
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

This is MIME letter


--=felis-related=20030526065413=7019
Content-Language: ru
Content-Type: text/html; charset=koi8-r
Content-Transfer-Encoding: 8bit


<!--
--*--
-->
<HTML lang="ru"><HEAD> 
<TITLE>Subscribe.Ru : Клерк.Ру: Практическая помощь бухгалтеру</TITLE> 
<META NAME="keywords" CONTENT="бухгалтер аудит бесплатные консультации экономистов и бухгалтеров москва интернет бухгалтерский форум экономический краснодарский край налог налоговая система налоги местные федеральные"> 
<META NAME="author" CONTENT="support@listtop.ru ведущий рассылки ToT"> 
<STYLE><!--  --></STYLE> 
</HEAD><BODY BGCOLOR=#EBD2A5 LINK=#660000 ALINK=#000000 VLINK=#000000 TEXT=#000000><IMG SRC=http://image.subscribe.ru/1.gif/tax.lawlisttop/20030526065403/=3405====n==t/m397137 HEIGHT=1 WIDTH=1><!--#include virtual="/archive/header.issue.shtml"--> 
<!--noindex--> 
<CENTER> 
<table style="background-color: #ebd2a5; background-image: ;" background="" bgcolor="#ebd2a5" width="100%" cellpadding="7" cellspacing="0" border="0"><tr> 
<td align="center" width=100%><B><font SIZE=2 color=#000000 style="color: #000000; font-size: 10pt;">Информационный Канал</font> 
<A TARGET=_top HREF=http://subscribe.ru/><font SIZE=2 color="#000000" style="color: #000000; font-size: 10pt;">Subscribe.Ru</font></A></B></td> 
<td align=right><nobr><font SIZE=2 color=#000000 style="color: #000000; font-size: 10pt;"></font></nobr></td> 
</tr></table> 
<HR NOSHADE> 
</CENTER> 
<!--/noindex--> 
<!--noindex-->
<!-- 3405 --><center>
<script language=JavaScript>
<!--
var seed=Math.round(Math.random()*65535);
document.write("<img src=http://engine.awaps.net/0/2687/001001.gif?0-0-"+seed+"-0-a:8207p:7367 width=1 height=1 border=0>");
//-->
</script>
<noscript>
<img src=http://engine.awaps.net/0/2687/001001.gif?0-0-0-0-a:8207p:7367 width=1 height=1 border=0>
</noscript>
<table border=0 cellpadding=0 cellspacing=0>
<tr><td>
<a href="http://link.subscribe.ru/5623/397137"><img src="cid:advert/adwatch/030512megafon.gif" width=500 height=100 border=0></a></td></tr>
<tr><td align=right><font size=1>Реклама</font></td></tr>
</table>
</center>
<HR NOSHADE>

<!--/noindex-->



<table width=100% cellspacing=1 cellpadding=2 bgcolor=#EFDFB7>
<tr><td>
<p><center><center>Здравствуйте, уважаемые клерки! <br>
Разрешите ознакомить Вас с анонсами материалов сервера
<b><a href='http://klerk.ru/'>Клерк.Ру</a></center>
</center></p>
<table width=100% border=0 bgcolor=white><tr><td> <strong>2-х дневный семинар </strong>по международным стандартам финансовой отчетности
(МСФО) на русском языке в Российской академии госслужбы при Президенте РФ. <strong><a href='http://klerk.ru/redir.php?id=4&url=http://www.iab.org.ru/28-04-03(3).htm'>Разработчик
- Институт Финансовых Аналитиков (Великобритания)</a></strong>. При участии гостей
из Великобритании, преподавателей МГУ им. Ломоносова. Приглашаются все желающие.
<a href='http://klerk.ru/redir.php?id=4&url=http://www.iab.org.ru/28-04-03(3).htm'><strong>Подробнее>>>></strong></td></tr></table>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/news'><b>Бухгалтерские новости:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>23.05 11:52 - <a href='http://klerk.ru/news/?2857'><b>В МНС стало приходить в два раза больше писем.</b></a>
За апрель текущего года в центральный аппарат МНС поступило 802 обращения граждан. По сравнению с мартом число писем выросло в два раза. Увеличение корреспонденции налоговиков объясняется ростом числа писем, связанных с налогобложением религиозных организаций. Кроме того, граждане чаще стали просить справки об отсутствии налоговой задолженности. <br>
<li>23.05 11:56 - <a href='http://klerk.ru/news/?2858'><b>Налог с продаж может вернуться </b></a>
Руководители торговых сетей &laquo;М.Видео&raquo;, &laquo;Патэрсон&raquo;, &laquo;Седьмой континент&raquo;, &laquo;Крокус Интернэшнл&raquo;, &laquo;Эльдорадо&raquo;, &laquo;Спортмастер&raquo; и других, рассказали журналистам, что 20 мая ряд законодателей, предложили сохранить налог с продаж (НСП). Напомним, что в соответствии с Федеральным законом &#8470; 148-ФЗ от 27.11.2001 НСП с 1 января следующего года платить будет не нужно. <br>
<li>23.05 12:05 - <a href='http://klerk.ru/news/?2859'><b>В США снижают налоги.</b></a>
Налоговое бремя в США будет в ближайшие 10 лет уменьшено на $330 млрд.<br>
<li>23.05 12:14 - <a href='http://klerk.ru/news/?2860'><b>Как выплачивать пособия за счет соцстраха, налогоплательщикам, перешедшим на &laquo;упрощенку&raquo; или переведенным на ЕНВД.</b></a>
Налогоплательщикам, перешедшим на &laquo;упрощенку&raquo; или переведенным на ЕНВД, разъяснили, как выплачивать пособия по временной нетрудоспособности своим сотрудникам. Эти разъяснения утверждены постановлением Минтруда России и ФСС России от 18.04.2003 &#8470; 20/43, недавно зарегистрированным в Минюсте России.<br>
<li>23.05 15:16 - <a href='http://klerk.ru/news/?2866'><b>Термин "недобросовестный налогоплательщик", который Конституционный суд изобрел почти два года назад, уже принес бюджету 3,2 млрд руб.
</b></a>
Налоговики изменили тактику поведения в судах<br>
<li>25.05 01:48 - <a href='http://klerk.ru/news/?2871'><b>УМНС по Санкт-Петербургу обзавелось собственным сайтом</b></a>
Представленная информация позволяет пользователям оперативно и четко выяснить любой вопрос, касающийся взимания местных налогов и сборов, налогообложения юридических и физических лиц. Консорциум намерен ежемесячно актуализировать содержание раздела.<br>
<li>25.05 02:01 - <a href='http://klerk.ru/news/?2872'><b>В России может появиться "детский налог"</b></a>
Ввести в стране "детский налог" рекомендовали участники Парламентских слушаний, которые провел в Госдуме Комитет по делам женщин, семьи и молодежи по проблеме законодательного обеспечения государственной материальной поддержки семей с детьми. Как сообщила председатель комитета Светлана Горячева, для реализации этого предложения необходимо увеличить государственные ассигнования на повышение размера ежемесячного пособия на ребенка. "Сейчас оно равняется 70 руб., что всеми признается недостаточным", - пояснила она.<br>
</ul>
<hr width=100%>
<table width=100% border=0 bgcolor=white><tr><td><a href='http://klerk.ru/redir.php?id=57&url=http://www.icas-ane.ru'><strong>Программа
профессиональной переподготовки "Международная практика бухгалтерского учета в
менеджменте" разработана преподавателями АНХ при Правительстве РФ и ведущими специалистами
Института присяжных бухгалтеров Шотландии (The Institute of Chartered Accountants
of Scotland, ICAS)</strong>. </a></td></tr></table>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/articles'><b>Бухгалтеру:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>25.05 01:05 - <a href='http://klerk.ru/articles/?2869'><b>Импорт материалов через посредника</b></a>
Российские организации могут приобретать импортные материалы через посредников, заключая соответствующий посреднический договор. В посредническом договоре (чаще договоре комиссии) должны быть определены наименование товара, вид, тип, сорт, класс, количество и т. п. <br>
<li>26.05 05:44 - <a href='http://klerk.ru/articles/?2874'><b>Как отправить работника в отпуск</b></a>
Оплачиваемый отпуск должен предоставляться работнику ежегодно. За первый год работы отпуск предоставляется сотрудникам, которые отработали на предприятии без перерыва более шести месяцев. По соглашению между директором организации и работником отпуск может быть предоставлен и раньше этого срока.

Некоторые работники по закону могут пойти в отпуск и до истечения шести месяцев работы. Это право предоставляется женщинам перед отпуском по беременности и родам или сразу после него, несовершеннолетним и другим работникам.<br>
<li>26.05 06:15 - <a href='http://klerk.ru/articles/?2876'><b>Постановка     на учет по месту нахождения недвижимого имущества</b></a>
В Постановлении Пленума Высшего Арбитражного Суда Российской Федерации от 28 февраля 2001 года &#8470; &laquo;О некоторых вопросах применения части первой Налогового кодекса Российской Федерации&raquo; разъясняется, что статья 83 НК РФ регламентирует порядок постановки на налоговый учет, как самих налогоплательщиков, так и принадлежащего им имущества.<br>
</ul>
<hr width=100%>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/law'><b>Юристу:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>25.05 01:42 - <a href='http://klerk.ru/law/?2870'><b>Налоговые санкции: некоторые проблемы взыскания</b></a>


Хотя с момента введения в действие части первой Налогового кодекса Российской Федерации (далее -- Кодекс, НК РФ) прошло более четырех лет, однако арбитражные суды нередко испытывают затруднения в вопросах применения отдельных ее положений. Тенденция роста количества дел, возникающих из налоговых правоотношений, стала особенно заметна в 1999 году, с момента введения в действие части первой НК РФ, Федеральных законов от 09.07.99 &#8470; 154-ФЗ "О внесении изменений и дополнений в часть первую Налогового кодекса Российской Федерации" и от 09.07.99 &#8470; 155-ФЗ "О внесении изменений и дополнений в Федеральный закон "О введении в действие части первой Налогового кодекса Российской Федерации", а также постановления Конституционного Суда РФ от 15.07.99 &#8470; 11-П "По делу о проверке конституционности отдельных положений Закона РСФСР "О Государственной налоговой службе РСФСР" и Законов Российской
Федерации "Об основах налоговой системы в Российской Федерации" и "О федеральных органах налоговой полиции". <br>
<li>26.05 06:11 - <a href='http://klerk.ru/law/?2875'><b>Обсуждаем статью 304 нового АПК РФ</b></a>
В соответствии со ст. 8 Федерального закона от 24.07.2002 &#8470; 96-ФЗ "О введении в действие Арбитражного процессуального кодекса Российской Федерации" с 1 января 2003 г. вступила в силу глава 36 Кодекса "Производство по пересмотру судебных актов в порядке надзора". В новом АПК РФ положения данной главы были подвергнуты наиболее существенному реформированию.<br>
<li>26.05 06:21 - <a href='http://klerk.ru/law/?2877'><b>Процессуальные новеллы рассмотрения споров в сфере исполнительного производства</b></a>
В АПК РФ 2002 г. нашли свое разрешение многие моменты процессуального порядка рассмотрения споров по делам, связанным с применением законодательства об исполнительном производстве. Правовому регулированию этих вопросов посвящен, в частности, ряд статей главы 24 раздела III и раздел VII Кодекса. Новеллы в этой области столь существенны, что на их анализе следует остановиться более подробно.<br>
</ul>
<hr width=100%>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/reference/blank'><b>Бланки:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>26.05 06:30 - <a href='http://klerk.ru/reference/blank/?2878'><b>Бланк нового платежного поручения 2003 (MS Excel 97-2000)</b></a>
Бланк нового платежного поручения 2003 (MS Excel 97-2000) /1 июня 2003 года вступает в действие)/<br>
</ul>
<hr width=100%>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/humor/other'><b>Юмор > Разное:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>23.05 12:45 - <a href='http://klerk.ru/humor/other/?2861'><b>Без бумажки ты &mdash; букашка (история одной проверки)</b></a>
Это не я, &mdash; отвергла я инсинуацию. &mdash; Это маразм, но все по закону. А что же вы думали, за открытое общество и интеграцию в мировую экономику никто не должен платить? Да и бог с ним, с Алексеем. Он &mdash; ваша проблема. А мне, честной налогоплательщице, нанесен серьезный ущерб. Брошена тень на мою кредитную репутацию. Обсудим размер компенсации? В порядке, так сказать, досудебного урегулирования? <br>
</ul>
<hr width=100%>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/humor/anekdot'><b>Анекдоты:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>
Выходит главбух из кабинета налоговой,смахивает пот со лба и устало вздыхает:уф,сдал!Ему из очереди кричат:дай списать!!!<br>
<li>
Сдавший отчет по НДС бухгалтер выходит из налоговой, унее спрашивают: ну как, она отвечает - лучше оргазма!!<br>
<li>
Вообще-то я не бухгалтер, а программер 1С, но пара приколов из моей жизни этому серверу не помешают:<br />
<br />
Я: Скажите, здесь находится ЗАО ХХХХХ ???<br />
охранник : может и здесь ... но это тюрьма ...<br />
 (ошибся адресом, называется ...)<br />
<br />
<br />
<br />
<br />
<br>
</ul>
<hr width=100%>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://klerk.ru/relize'><b>Пресс-релизы:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<ul>
<li>25.05 01:27 - <a href='http://klerk.ru/relize/?2838'><b>Совместная акция Клерк.Ру и Яхтенного Агентства "МАРИН.РУ". Каждому клерку при заказе тура - скидка! </b></a>
Сегодня мы предлагаем Вашему вниманию не совсем обычную информацию - мы открываем
на нашем сервере новый раздел, не имеющий отношения ни к бухгалтерии, ни к финансам,
ни к банкам&hellip;Раздел <a href="http://klerk.ru/marin/" target="_blank">"<font color="#0000FF">Активный
отдых на море</font>"</a>. <br>
<li>25.05 14:51 - <a href='http://klerk.ru/relize/?2848'><b>Выездная практическая конференция.Налоговое планирование бизнеса.</b></a>
Под эгидой Палаты Налоговых Консультантов Вашему вниманию предлагается Совместный
Проект <a href="http://klerk.ru/redir.php?id=28&url=http://akmr.ru"><font color="#0000FF">Учебного
Центра ООО &laquo;АКМР&raquo;(ГК Русаудит)</font></a> и Консалтинговой Группы &laquo;ЭКОН-ПРОФИ&raquo;.18-20
июня 2003 г. состоится выездная практическая конференция: "Налоговое планирование
бизнеса".<br>
<br>
<li>26.05 00:28 - <a href='http://klerk.ru/relize/?2873'><b>Спортивный клуб. Система клубного учета.</b></a>
<a href="http://klerk.ru/redir.php?id=75&url=http://www.effinf.ru/"><font color="#0000FF">Компания
  &laquo;ЭФФЕКТ ИНФОРМ&raquo;</font></a> представляет уникальный продукт &laquo;Спортивный клуб&raquo;,
  разработанный на базе &laquo;1С:Предприятие 7.7&raquo;. Новая программа предназначена для
  спортивно-оздоровительных учреждений и клубов и решает основные задачи: учет
  клиентов, учет посещений мероприятий, проводимых в клубе, управление расписанием
  клуба и учет оказанных услуг. <br>
</ul>
<hr width=100%>
<tr><td bgcolor=#E9D9B7>
  <a href=http://klerk.ru/calendar><b>События календаря налогоплательщика:</b></a>
  </td></tr><tr><td bgcolor=#E0D0AF><a href="http://www.klerk.ru/calendar/?_day=26&_month=05&_year=2003">26.05.2003</a><br><a href="http://www.klerk.ru/calendar/?_day=27&_month=05&_year=2003">27.05.2003</a><br><a href="http://www.klerk.ru/calendar/?_day=28&_month=05&_year=2003">28.05.2003</a><br><hr width=100%></td></tr><tr><td bgcolor=#E9D9B7>
  <b><a href=http://klerk.ru/events>Семинары, тренинги, конференции</a></b>
  </td></tr><tr><td bgcolor=#E0D0AF><a href="http://www.klerk.ru/events/?action=detail&idev=72">26.05.2003 <b>Семинар &laquo;Учет и порядок налогообложения в организациях, имеющих филиалы и иные обособленные подразделения&raquo;</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=62">27.05.2003 <b>Новая Пенсионная Реформа. Новый порядок установления государственных пенсий, пособий и других социальных выплат</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=73">28.05.2003 <b>Семинар &laquo;Делопроизводство в кадровой службе&raquo;</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=64">28.05.2003 <b>Наем, перевод, увольнение работников в современных условиях. Типичные ошибки работодателя при заключении, изменении, расторжении трудового   договора в свете нового трудового законодательства</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=65">28.05.2003
<b>Программа практической выездной конференции &laquo;Профессиональные комментарии по проблемным вопросам бухгалтерского и налогового учета&raquo;</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=63">29.05.2003 <b>Делопроизводство в кадровой службе</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=77">30.05.2003 <b>Бесплатный Демо-день 1С для МЕДИЦИНЫ</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=70">30.05.2003 <b> Семинар &laquo;Учет основных средств, материально-производственных запасов и нематериальных активов&raquo;</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=59">30.05.2003 <b>Семинар: Автоматизированные системы делопроизводства и электронный документооборот</b></a><br><a href="http://www.klerk.ru/events/?action=detail&idev=67">30.05.2003 <b>Налогообложение строительных организаций: возмещение НДС, уплата налога
на прибыль</b></a><br><hr width=100%></td></tr>
<table width=100% border=0 bgcolor=white><tr><td><strong><a href='http://klerk.ru/redir.php?id=65&url=http://www.supermb.ru/'>Бесплатный Демо-день 1С для МЕДИЦИНЫ </a></strong> <br>Многие медицинские учреждения
являются бюджетными организациями, поэтому для них актуальной темой является автоматизация
специфических для бюджетников аспектов учета. В программу демо-дней будет включена
и эта проблематика, если при регистрации достаточное количество участников выразят
свою заинтересованность в ней. <br><a href='http://klerk.ru/redir.php?id=65&url=http://www.supermb.ru/'><b>Подробнее>>>>></b></a></td></tr></table>
</td></tr><tr><td bgcolor=#E9D9B7><a href='http://forum.klerk.ru/'><b>Форум - Горячие темы:</b></a></td></tr><tr><td bgcolor=#E0D0AF>
<table cellspacing=0 cellpadding=0 border=0 width=100%>
<tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11579 class=q>СРОЧНО ндфл-2</a> <span class=dt>(1)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11578 class=q>Прежде чем задать вопрос...</a> <span class=dt>(1)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11577 class=q>использование прибыли</a> <span class=dt>(1)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11576 class=q>Скорбный лист &#8470;2 Reloaded</a> <span class=dt>(0)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif"
border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11575 class=q>Раритет...</a> <span class=dt>(1)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11574 class=q>Два ИНН. Что бы это значило?</a> <span class=dt>(4)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11570 class=q>Расходы по приобретению товара до перехода права собственности</a> <span class=dt>(0)</span><tr><td width=16><img src="http://klerk.ru/im/arb.gif" border="0" alt="" width=15 height=15> <td><a href=http://forum.klerk.ru/showthread.php?threadid=11569 class=q>Частичный переход на упрощенку</a> <span class=dt>(0)</span></table><hr width=100%>
</td></tr><TABLE align="center" width=300 CELLPADDING=2 CELLSPACING=1 bgcolor=white>
<FORM ACTION='http://subscribe.ru/member/quick' METHOD=GET>
<TR><TD bgcolor=#EFDFB7><INPUT TYPE=hidden NAME=action VALUE=quick>
<FONT SIZE=-1>
<INPUT TYPE=checkbox NAME=grp VALUE='tax.lawlisttop' CHECKED>Клерк.Ру - Практическая помощь бухгалтеру<BR>
<INPUT TYPE=checkbox NAME=grp VALUE='comp.soft.prog.klerk1c' CHECKED>Автоматизация предприятя <BR>
<INPUT TYPE=checkbox NAME=grp VALUE='bank.banks' CHECKED>Бухгалтерский учет в банках<BR>
<INPUT TYPE=checkbox NAME=grp VALUE='marketing.boss' CHECKED><b>Управление.Менеджмент.Персонал </b><BR>
</FONT></TD></TR>
<TR><TD bgcolor=#EFDFB7><INPUT TYPE=text NAME=email SIZE=20 MAXLENGTH=100 VALUE='e-mail' class=input><INPUT TYPE=submit VALUE='OK' class=input></TD></TR>
</FORM></TABLE><hr width=100%>

<tr><td bgcolor=white><table width=100% border=0 bgcolor=white><tr><td>Приглашаем авторов к сотрудничеству.<br />
Присылайте ваши статьи на адрес <a href='mailto:totl@klerk.ru'> tot@klerk.ru</a>,<br />
и мы их с удовольствием опубликуем на нашем сервере и в нашей рассылке.<br />
Реклама на сервере<a href=' http://klerk.ru/advert/'> http://klerk.ru/advert/</a><br />
<b>Бухгалтерская Баннерная Сеть</b> <a href='http://members.klerk.ru/'>http://members.klerk.ru/</a></td></tr></table><br />
</td></tr></table>


<!--noindex-->
<!-- t --><hr>

<center>
<table border=0 cellpadding=0 cellspacing=0 width=80%><tr><td align=center>
<table
style="FONT-FAMILY: arial; background-color: white;" bgcolor="white"
border=1 cellpadding=0 cellspacing=0><tr><td>
<table border=0 cellpadding=3 cellspacing=0>
<tr>

<td>
<a href="http://subscribe.ru/catalog/hscope.oven.main.weekly"><font style="color: black; text-decoration: none" color=black size=3><b>Овен: Общий Еженедельный гороскоп от Providence.Ru</b>.</font><br>
<font style="color: black; text-decoration: none" color=black size=2>
Овен Общий Еженедельный гороскоп Providence.ru
</font>
</a>
<table border=0 cellspacing=0 cellpadding=0 width=100%><tr>
<td width=40% align=left><b><a href="http://subscribe.ru/catalog/hscope.oven.main.weekly"><font style="color: black;" color=black size=2>Подписаться</font></a></b>.</td>
<td width=10%>&nbsp;</td>
<td width=50% align=right valign=bottom><nobr>
<a href="http://subscribe.ru/catalog?gold"><font style="color: black;" color=black size=1>Золотые рассылки Subscribe.Ru</font></a>
</nobr></td>
</tr></table>

</td></tr></table>
</td></tr></table>
</td></tr></table>
</center>
<HR NOSHADE><CENTER>
<iframe src="http://ad.adriver.ru/cgi-bin/erle.cgi?sid=458?bt=1?pz=3?sz=/economics.tax?rnd=675350799" frameborder=0 vspace=0 hspace=0 width=468 height=60 marginwidth=0 marginheight=0 scrolling=no><a target=_top href="http://ad.adriver.ru/cgi-bin/click.cgi?sid=458?bt=1?pz=3?sz=/economics.tax?rnd=675350799"><img src="http://ad.adriver.ru/cgi-bin/rle.cgi?sid=458?bt=1?pz=3?sz=/economics.tax?rnd=675350799" alt="-AdRiver-" border=0 width=468 height=60></a></iframe>
</CENTER>
<CENTER><HR NOSHADE><TABLE style="background-color: #ebd2a5; background-image: ;" background="" bgcolor="#ebd2a5" cellpadding="7" cellspacing="0" BORDER=0 WIDTH=100%><TR> 
<TD ALIGN=left valign=top><A TARGET=_top HREF=http://subscribe.ru/><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">http://subscribe.ru/</font></A> 
<BR><font size=2 color=#000000 style="color: #000000; font-size: 10pt;">E-mail:</font> <A HREF=mailto:ask@subscribe.ru><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">ask@subscribe.ru</font></A> 
</TD><TD ALIGN=right valign=top> 
<A TARGET=_top HREF=http://subscribe.ru/member/unsub?grp=tax.lawlisttop&email=goncharova@iph.ru><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">Отписаться</font></A> 
<br><A TARGET=_top HREF=http://link.subscribe.ru/noad><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">Убрать рекламу</font></A> 
</TD></TR></TABLE></CENTER> 
<!--#include virtual="/archive/footer.issue.shtml"--></BODY></HTML> 
<!--/noindex-->


--=felis-related=20030526065413=7019
Content-Type: image/gif;
  name=_adwatch/030512megafon.gif
Content-Transfer-Encoding: base64
Content-Location: advert/adwatch/030512megafon.gif
Content-ID: <advert/adwatch/030512megafon.gif>

R0lGODlh9AFkAMQAAPbz9ioCYfbQAQSaBF85irEFPn5fo5fXl6+Zxt+mF7+v0cfpxXgGV2XDZfvs
mN7S5JqCt+zi7fKdrS+xMvjcSM/C2+puE3FaXun13+pdduMqNKqIOz4Qe94BKf///73reiwAAAAA
9AFkAAAF/2AnjmRpnmiqrmzbcTBXlHFtx0xZ2F7vfcCgcEgsGo/IpHLJbDqf0Kh0Sq1ar1ina8vt
elm1GWl3K5tuvl92zW673/C4fE5nfu/4vCpsYpRrOTpoPnWFhoeIiYqLcnqOj3eAJwV+NgwMYjQ2
BGmMnp+goaKjVpCmpyuVMI5lnISksLGys7RwqLe4IqoyebsxBp21wsPExcO5yKZkMXh/HAjBxtJS
MYkcVddG2dPcyd6Ovl7LNwQR0UvbH+ncs+uG29VAMEHz6vXy2kLxQ/v4VP37+vkz9q3gnXEwMq1A
eAPaOSXw3LEjJbEOPHryIqrDyFFftYv6OAp8AvIiyIzTuv9QwoRp0iUOLy8F6nBpJaZMBVbqHLES
pp+aX3zBzDmJkrMYBACkUWNkhMiNGe9FnEpvXrarHqnyQxk1arqPNaDWA3gvq72vYwP60wp148mR
JzFem9t2a8i3dutWjDcyZFu6AwFnnVuWb9k5XRgQMMCYg4kCAQhAQKCgMgIDQwssZsyYwEzFnBvP
8COZcmUIBALM5FKDwIUNCRIImB17wwUCR2tUWMq0iNO1Yu92xIrVLfDAf7d+lfv0uHHkyf1GN9m8
eEnm9qB3PMscsEB3UrdHH6h8fF7qx8EPxy4+joucfhT0qOB4DAcIEZT6AABAgWfN/AUIAS87QBAg
ABEQYJT/AvqlAQACMInDwQWxzWbhhbTZlptDSyHx23PFbXcdVdZVBdZ3hbEX4orhrRWWdNfhE6N1
L9pg3FUvthfcjiIWMZZ4ce31XF09yihSjtqhh2QjC1VigHw9PNDSCBwY0CB/+ykAU1JpPEAgBw84
6NkzV145oEItaCAbhmxemMAGuJUBAW89ONHicnitCKJ25NmVZ3M8lugcEXglN+OgyP1IJIzVGUme
RHT9+aiPji66DnpEqgcdcYDaksozDzToAX327TafAQQg0GBqVi5lQA4MtOpDgoqZ48GDjHHo5Wos
WLBmm8DSdsENBtLZG0QwqtXVDcH9YSKOh72VVmEtTkft/2HckcWWs2fpKW20ZvUJbV5emehXQEgy
C1eO6GoqHXfdWsUXYgtxwGB+PkiJEwemAmBAAAAbUMHA/3KZBgIB7MBhD7Qa/EBqATwzsH+8pqCB
BcFmfOEGSC3M2zvvHlERNhP1mcXIduYjMhTLgdIyIizsQMDMc85Xnwg7mDoqqhxEHPElrqSRYGRh
Cu1ZOT4gMHPPEQ/Vgq8aR03bYjobW/IUKF9tRdbIqqz1MTHDB0yUU+pScw8APFDBZQkByNu/Yxvt
R9VpK6C00y1IrbcACYhq9deABy44O1zE6gOpJMzt960PYKZYvqZqCWUFRSdICQFFLwVABbihecKv
e2tMgf+xDw1u+umof1J43PqO4ceToWqOm8EKFBuBAWH6a6rlZEBQga1d4rYCxhgmcMFtxxOwQegC
OEB6nalHL/309LpguM2uMwAwBzRX0KACkR2O+a22cr67Z5dsvxgEmXsAQQAqaNBmAjcsz/zzx1I/
UV/693/F6vkqm2LspoB/veRs9HHYM5YCocqxioCpeQmUPAAhFRAPQxyzAehsY5vXUIhNoyOdnfjn
P0RwrYRRkMoJVzaLwhVrVDejSdwSBJMAxC2B+arSlTDjwABwiD7a82HSYliCC2JwExhKTQwiBiwM
iLAJK0ThHKIoRShqJIVLEgUAyZYJxWTuAQiYDPDe5zD/3HwRBj2UlQceAAEIMAht/0oB6C40rCXa
z0K3mdnM7oihENLJQyLQUbvi1S1z2QhTf8HWvAKjQhI5pyTYgleSppWnRW5KOOIajqISCS20jItQ
0yJkXG4klkYS5lCSHCUdXJhD+6iRN17SIcNSczYyFg0AY/IYAyN0AvkBS4kx4OP9/taUQJYrUYwK
EaAQqadzVWpEwBFUKc2zqOxsUjA02tHLlMmp8ySKMMh8JI8mJc7sCCdSnWrUkJppiNVFID/0UQhk
BOa3/qCvHO/knA1DRSt+IehhlAgA+3gTAQhVbAS+bNMGFsrBOYbuicXswHpEmUxGXjMsi7RRuMjZ
LEOK/zNSS4LUnp5pJO90hZDwUiVKqeMdjC5TkiKqUXf8JCOZPis91iKhp97DPT1WjAyMaSMEeHaT
ns4ME0aVgVE71wGgCnWouDnoCIzIvIcSEx3p3KY2X+ook6qsm4ZCpjR/NDKRenWdXPEqWEsE1omy
dJzTwc6lQpbITHbUmxa9ZjjroJKc+BUFPZFJ2fz6V8LOwLAKEaxgPVcC0CXAAr6C2t4eG9k5QhQd
2hrXFTnJzlPmlR96XdYha8qsnIInRRY1FyOP1Mx5jfJbk5TXtU4K2k4miVyl3GQhQ6asIa3SIMBF
Aeg0QIKESs0CxcXQZavIUSRQkbl0hS6T8KAKqQZXBf+gK2LotHuh5Ur3u3J4LnincJD0CcyAROGJ
YsvWJMUytqmEFe6FiIvQvdF3BJa96nj3y9+USEgyCggTGB0nBtI81XH1qpJQidqHpKLAiPcVAVWB
FeEOGHc23u2vhjccCwnhjk4UowmZhOYfIrqOAG+c1YBmElBV9cfEEp6vCSRbvMdW+MIY1i+Hd8xj
T3jBi2gzB75e7AcOYakHWpIqkNGmHwCc6SUjXiOMLXwh5FpMA1iucH3blOEee/nL1VPveikxmrH5
y0BtRBur9HM7AuhsQJNY4HwWYytaMcCNwIMhCoybgDyoqU1+/BhJIjk9jZJFR2BOtG9owJkFMwZW
NYv/gA39Za/KpIZD/4pM+XhRglpFyTMCTZr2Jni4KXfAiFb2Ao4tFOgOpcxkhcZrWxVN60WTAExN
9oECWGLmNL8PBpUompdyYi81e+56FJSBYvRDH+4FtdQWw5CWWbBqCzlRx0L4kLs+6ZUTYfOk2wSX
izyp1dq2tlKgTMumFBVKvMJ03d+GqWEE1VlFzvtItHVpRTV5qROFa0bxbsIZDNBGBBg8jK+iyfjQ
NirUqEYzmx6NQ/xVsTv7AAI50Iyw/3OJG5q6A45NNbUnfKFWuzqi7XktR7vJbr3wSeXmUamKquKW
bbvcnCYVKaNwi6NMBWqmW9UmO6P5FJ3Pmpl8kute/9fKFYF3mmkAi7pqRMC9PDNsQFXHHk3OlvBO
vxDjTQXTLMVQAFkhbs9ztLGWsQxZh/bx2tgOgrZ9NG9uFh1E7e5kvymZ2mpSSuXK5OQ5u3qtvZuy
PIKZaFhTitOWfoek8s5oKjHK7pBy2yQ1Ck/ilzDwoBKcM4HonQKsDj6keWDX8OF6xWuZcTePXRdm
/ziVgRWb2rs9WM57HkmAFFe34pzoI3Vu7+9qqZljcq6PZDlO7fpzj6A7+PQOes/h6kxUHmqsd82a
Wo2fTb8f4Qy3vNV8WOKHqM+JMnBceDxfMPGuJ+7rrd94gT3eq6pqLPe6H7Sm2GWVpYP7ooRmW902
dP+q9W6bNRjLpC6shXycJWv9N24DSCMK+FluVS22hXmVxCKFF3nnBnlOd2uTQRkieBlIFYJw4wE8
1AMDImy8UGy3oiCIhWwVtGw2Q3ax1wK3Z38m90e1BjKI5jLRRSg9aAedtl4yQWxFAz7AgBm28j7t
pxoLtyuKoUdbYiu7IlD6UUGwB23UZn+Ahj+vMIRiOIZECFg4A4IXBw2T4QNww2wzwyEYpxnewx9j
MkFK82EecDufcYNpkoN6QwFwhz9kOIiEaGtbsGTi9z0w4YKMk0NIdUsK4mlRAjwIgxP0twXVFjWA
CIalU4ieOIRfwD3eozkGJWIpJj714WZKgUvEhof/+1GKIxArWHJ2LZABEeAAoUMB+MeJ0POJvgiK
4vA6AnN6RFVgVWJwdkNgYScZ+aEgTRUxBiCCqMFLPLEZPLMFGVA0GOAAFCA6DrA4nFhr4tUG43g6
5Tg9BxFQBnA7D6cDMuETqwEDc2I56gWP7IUzZHYTLpCNvLGNFPCPAOkADhCIvNiJIqNRKHSOWKCQ
b4CQFrFheiAznGaGj+F6ycZY74UH/FiQHBl3QDB3Pyg9DEkysDCS/6BhjvBXEhJgsOgNG9mRMGmQ
H2lMNzd5nzR9TLcs/FaAK8V38GaB0wRut2WA+1Zz/nZM2nJMN5VuQvl7aJVvKHldroMqflAQthiT
/1gZhrZWJEhXUtW3HgGndLgFeT0Xfdbkd2dVlsw3TYUSI8EnlpTyLm91d/7XX1J5lyKgARJgdVnZ
ka/2UYPhWUXHLkZ5eO+mFx9xd9tHSijygHP5eDOFkHr3TeRGfbz3LIIZTYQpc9CFl1Kpl+DYlwX5
lz/3MoMSWjkJTe4Wb2SVHsoXTld0dM73lNSnJLDpbs01TqiZdODlmcGVARIgmqJJmtvCd0FCmYRZ
LoGHmLLVlslJm5RnSWe1cuMxFQKYWarUF3UXc8ipW+PlmwWhAVcpnH0JhF7jfVsDRWsgXiYJa59Q
VpjUX9MGnqYAmuQ5nO+Zn0zQnid5Bfy5nuq5Yf8SkAH0iQsveZ9Z+YsKWmtpIwHzWaCqtpcIKpwL
WqFghjYD+qAQSm3jOaH4aaEgymFCM6Ab2gXiKQGh6aF+WTKcGaKjoFM+iJ5tAEskWqIrcKJ8qaJY
OUKEpggwOoY/ap4v2qNvQCcNmgEaWqA4qqMISpouKqT/6QZRWjLPEwEZaqMikAEZMIpM2qTfR5OQ
0kiiNEijhW4EmFKZJ6aq1S7fdkiHJyR9B1u7RVtCeBfRmVt1d5RyWltKyXhxKhd3ipNAGZhz6m2J
5w5guDlXSp8n2j5dep+AJFFK2ZVvWU6+1X1g+VJ/cn1N14Gb53s15ZS02RG/wYB213yXhJM/yJr/
3Gd8ulmdLuJNyzl0iMqLDzCgSPqZJyqhj6qikVqBiZmpDchZgskppjp8p6R5K+WVkCR56yKdpERR
FPgBpSprzsSdQul49vaApZmmzemWqaSYskqBWlGrHGmlWopl3oBlwCkBjtqrE/qXgadV2AerLDev
rfp8xDeYl0RT+AqY04mscgemXAlaihdXLec1rEqWq0lOrfWvI+WWs/YBWRkBt5quSYqJ7CoB7pqj
8BqvVrSB2UJz5AqWCWspqMmm8ZKsi1edwWqUdSp4LtucCHiQpjqoOtmUw1qzSTmzAedIEJh0m2Wd
fzoE5IkgFYCrSKqu1MauWsqx+PKxHwtd2heE/8Qwpef5pEWAoAFipUq7tFmWZVr6tFCboqLJOSiW
bAsHr1TbP1gbl1prBFI7t6QDIQuEde/KpHG7t9BFt367FAOCOZT2So/Kt4aLQn+buBgARruxOQqw
AEfWqwtwuJRLPYnrtwcwAQegOZm7AB+LAZUbuqlzuXMLAA0wABPguT2AAaebulI7uaIbu4FDunN7
AAOAug1wAA1wugOwuVILurIbvFdDu7/Lu7d7u5rrt8ArvMwrDcRbvBMQvZqrusoLu817vbXAixFg
N2EUYLxRN2FEGcCTNpTzO0sRAeUbOx6AAQvQvu77vgTJvu0rKu2LAQAgv06Ev/L7vvy7ABjAvv+R
m5Xsi70EHAtgWFBxghQvlIfTWAPDOCpUuMCNwz1VUjSZi7qoOwEYnLw+gAHRi7rUuwAa7Lod3Lq7
u8EjPMID0AALcAAu7LvP28EC2Y2aKJAEGcM4nMM6vMM8TDoT/AfF8sPkECZYBwNqZLdGvIrGe7xM
TL0eYLvHC8NQTMI9sADHu8RMzMQNwL662wA4DADc6IUCoIs33MNmfMaJa7Zo3KUPAwOLQRkNjGuY
wT1uxDYwoCpznMRwVAM148HI2wATAMjIG8IafMU+wLtbnAZTrLuB/MG3C8iAfAD/28IwTLr+KMYl
N5BrvMmczKQLAMipW0Ck1skqejtufIpIjAD/zeaKNHQfprw0sqIlFCxnVgzC98u6j9wgWNwASuHH
K7wUvJu693u/hbzF/+tEaly6YYzJILSLpPzM0MyJuBzF7xMZoxzNomm3FrkfqBGNWHc2SMYYAzM7
mNEqgxsnFpzLaFPMPlDLgYy8TlTLvesgiJwGIny7TpzDy8zMwKKL2PzPAF3FWdy7CBN1uhTQ5xon
4Lwf70Rp3KPKZZJsCiZLCXQ3plfPVVzIvjvNB+DOnjvFTnzP8+wDIM3DuMjPUePM53sZM8MYo4fQ
MP238szEB1DQBh3TMCnL28wf+XFkRexseHZx8jggrTIgbiSPq8u7MOzRPTDFAMDUUxyI8uzE/1G9
wzSM0pp4wxHw0zawwDj91SoKAIWcxTUtdRGTObhyzRVAcMnMkf0xGXAd1I+KdUfc0pthsXncGgby
ynajQw/jZt+c0fhM0vC8vhrtASINuYgsKiWNNhiNwxhw1Vid1Wkgy0exzWCd2eQJxUyswWVt1nED
PgBTNRHANJFGOQ+Q2pWD2qqtFNvbPl5i1lHHL10yMJTTZKndJer7PAq9Hwnsxq4NVQ1BQ5gDIVZi
3D8MJe58bab7yE2NvKur0b5cyR4QzA0y3Tkc2ZOdi9dm2blB25od3n2JxZuruTbNNBxgKzYdN+4T
dcBAH2bNAQgCMVIXJhCjM6mRKlriQ5cRMf97LHVI8wCa5gOpkbdLESccstWdgdSz8gC1k8dPMjsF
VcGYEWCzk86/vM63u7kinbstrNEiXcli7dztXMj5bMmSvd1SA4ixBAPHcxtL1DMxYODiXeOkgwED
zcLmLdsBACUIg85o48Y2REHQ2GhpEzChsTk+MzaSlt4vGACunRq78WsE53CcIOCm5wFSDoYILjTv
NMcI4OC7vUZzHI1JTNQQUg6rbCtKrR8hXt0DrcWNLdgj/dyoW8Z/CwApruIrnsAEYCEbEDGLsRi/
YOOGLs1xvuHnHXU+bkPvUzMIQ3BDjjAQYL8YgC8CbgD2K34o2OP/EiYVED630jO2suU9M0H/pR0A
D9DkPT00NE7genwwbjyN6wi4Q43UgYsb56fH2C3Qdy7SiZ67hU3Yg03siYyV7Lu7oLy7Hd2Re87n
UZNBPXNHcWIqzQYDVXPo2p4GOD7QmosBNu0zQtTeBrAAEaMUUh7pRB4ZFGwlWC4qoc4J6h7vsxQA
pR4A3gMDeZYaoyfjMZ7tdFLE7PNPRZwqMYAfPG3RBYTt7oMUoQLm62vdh4y8zY26uuvCgoy7UXzM
nE3FFe/FMfnh0jvy0pu7eL4UJ50xDLXyDOWHoVNHMHBHSEGFhb7tNt/BcX4AjUPfUtfoVsLvAs4B
5E7kSzUnWO4qNmQ35w4APWMqPaMUsbTq/1nHhj2e6nqEG6oOhpyDFAv+C61cJZwRAwhA3ET8C3SI
7cAOwxzN2fm8yGPdyFp83YfdkaxL8nZP8tTdj8++MUdxAVj927NTA03TNEZ884bvAWMdxQgj4/mN
Rio45KX36ENP6bcyzGs0abMCdebX6WDfM40x5B7Q9PvR9JJWDsO85WDI1W58N9BwN+RgILJc60Us
H1ufFJx9AHL/yOy8FGyPxWTdIFNN93c//CN/4mmw93zvDMIkxsDGEs7g/Nxz+DfP2dS8hL/DCaiR
NAFwAU8eMU70PsDw40+lKu9+cZHxVJpGabJdJbZSMKaR35ef5aiv9aiiRwN/GY271ldPcP/WDgKG
gQCeIkJlBY1AMzVH6dFYcx93s9C9t+h4hwmReMjtfMAbxud8emzFKbUKa0Idgi23y71wwuJxwstN
oNPqsjlc6HQK4/E7HiZA8/o9v+//AwYKDhLqAQwgJh5AECgQQCAQIBgo9EAEGNBcBkBoYpoEhIpy
RDwEEMwAhFb4EAQg1FRUcAQoVET4YLiKnj54mJLSALiyFhofIyfzvUxdEFxcWFE15FGYXRPMjRFc
CyRkg3OEX1yHMcB1MGjXpd8pv8PHy8//HSQiHiDwimb2RCj4oqEAAZYHAGnIUmDLFgAAB2n8K+bv
YQ9ZeiogyKgACwCLFSvMoCdyJLIFVQj/gKsSjQoPJ1q6dUmgbQy5axtozeSwARuHc+gKFGAAFF27
MP1IIk2qNKk9Rfr2GQi5dCrVqlOZFXGGksCUO+KmUHNiDSaXmzl1dgMjJsBaDmy8qGVHlKgcMZ2s
4s2r98kQfJtCcUixdzDhwntMUkEpjmsRA9BWTmnZg2wXtTnfesmWk9s1mWHmztUW0DDp0vAiDMl3
B8Jo065fKx1yEpo0Kwd8vKQswLI2AphjJtiwJg1My0J/1p1zFzbz5n1KAIgQQarz6tYLYa2tvUhY
GmMpy2TLFictzrrPc9F8dhv16+7fw48vvwfWDfa3E7G/gbsP9AkuOPYMNM8QsBN6B36zC54YqMzX
oIMP0hACADs=


--=felis-related=20030526065413=7019--
