Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 02:19:32 +0400
X-Deliver-To: krylova@iph.ru
Received: from mx7.mail.ru ([194.67.23.27] verified)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187624734 for krylova@iph.ru; Mon, 26 May 2003 02:22:08 +0400
Received: from mail by mx7.mail.ru with local
	id 19K3sW-0001Hc-00
	for krylova@iph.ru; Mon, 26 May 2003 02:22:08 +0400
X-ResentFrom: <landysh_2000@mail.ru>
Received: from [144.137.110.75] (port=2613 helo=CPE-144-137-110-75.nsw.bigpond.net.au)
	by mx7.mail.ru with smtp
	id 19K3sS-00012C-00; Mon, 26 May 2003 02:22:06 +0400
From: =?koi8-r?B?7u/36e7r4SDp+iDz++E=?= <wmwlyy75@web.de>
To: siozjmfzgcae <siozjmfzgcae@mail.ru>
Subject: (Archive Copy) =?koi8-r?B?7OX09f7p5SD64e31/uHs6T8gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg?=
	=?koi8-r?B?ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg?=
	=?koi8-r?B?ICAgIMTE3NbS1sDWzCAgIM/Vxc4gICAgzNzUwdLWxcIgICAg1MfJ2tHC0A==?=
Date: Mon, 26 May 2003 02:22:52 +0400
Reply-To: wmwlyy75@web.de
Mime-Version: 1.0
Content-Type: text/html; charset="koi8-r"
Message-Id: <E19K3sS-00012C-00.wmwlyy75-web-de@mx7.mail.ru>
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru



<html>
<head>
	<title></title>
</head>

<body>
<center><IMG src="http://kp-masters.2itb.com/newfolder/logo.jpg" border=0></center>
<CENTER>
<table border="0" cellpadding="3" cellspacing="0" width="520">
<tr>
<td colspan="2" align="middle"><STRONG><FONT face=Tahoma size=6>НОВИНКА ИЗ США</FONT></STRONG></td>
</tr>
<tr>
<td valign="top"><IMG src="http://kp-masters.2itb.com/newfolder/fanar.jpg" border=0></td>
<td valign="top"><center><FONT size=4>Впервые<br><b>В РОССИИ</b></FONT><br><br>FLOWTRON - USA Northern Lights, Inc. представляет<br><font color="#ffffff" size="1">ппС   UUWSY </font>
<br><u><i><b>Электронный "КИЛЛЕР" насекомых ДЛЯ НАРУЖНОГО ИСПОЛЬЗОВАНИЯ</b></i></u></center><br><FONT size=2>Мы предлагаем - одно из лучших устройств, предназначенных для привлечения на свет и уничтожения летающих насекомых.</FONT></td>
</tr>
<tr>
<td colspan="2">
<P align=justify><STRONG>&nbsp;&nbsp;&nbsp;"КИЛЛЕР" предназначен для привлечения чувствительных к свету летающих насекомых и уничтожения их "чистым" способом без применения опасных для здоровья ядов, аэрозолей или химикатов. Насекомые летят на свет и гибнут, пролетая сквозь сетку, к которой подведен ток. Наружная решетка предохраняет детей и животных от соприкосновения с внутренней сеткой, находящейся под высоким напряжением. "КИЛЛЕР" предназначен для работы в режиме 220-240 В / 50 Гц.</STRONG><font color="#ffffff" size="1">чцлнъ   </font></P><P align=justify>&nbsp;&nbsp;&nbsp;Невидимые для человеческого глаза ультрафиолетовые лучи, являющиеся наиболее эффективным средством привлечения насекомых, вырабатываются специальным покрытием, нанесенным на внутреннюю поверхность стекла люминесцентной лампы</P></td>
</tr><tr><td colspan="2" align="middle"><b><FONT size=4>Действует на територии радиусом в 35 метров</FONT></b></td></tr>
<tr>
<td colspan="2"><b>Прекрасно работает по борьбе со следующими летающими насекомыми:</b><br>
<ul>
<li>КОМАРЫ<font color="#ffffff">HWLYZP оюякК </font>	
<li>МОСКИТЫ
<li>МУХИ<font color="#ffffff" size="1">RLD чРщЦАя  </font> 
<li>ОВОДЫ
<li>МОШКА<font color="#ffffff">LJO  </font>
</ul>И ДРУГИМИ<font color="#ffffff" size="1">ELXP   </font>
Летучими насекомыми.
</td>
</tr>
<tr><td colspan="2"><center><STRONG><FONT face=Tahoma size=4>ЦЕНА:</FONT></STRONG></center><b><FONT size=4>Розница, 1-5 шт - <FONT color=#cc0000>135 у.е.</FONT><br>Мелкий опт, 6-20 шт - <FONT color=#cc0000>115 у.е.</FONT><br>Опт, от 20 шт - <FONT color=#cc0000>100 у.е.</FONT></FONT></b>
</td></tr><tr><td align="middle" colspan="2"><b><FONT face=Arial color=#cc0000 size=5>КОЛИЧЕСТВО ОГРАНИЧЕНО</FONT> </b></td>
</tr><tr><td colspan="2" align="middle"><STRONG><FONT size=4>Наше представительство в г. Москве<br>тел: (095) 240-4854<br>8-916-536-4175<br>8-902-147-5473</FONT></STRONG></td></tr>
</table></CENTER>
<br><br><br>
<font color="#ffffff" size="1">ябннп    лщякоцорм абемехопяп     еоряъхгдщ FSPFT   SQQDFOH    APNPFEIOYZ EJRIWTAAVOI </font>
</body>
</html>

