Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 01:24:17 +0400
X-Deliver-To: klescheva@iph.ru
Received: from [212.16.212.6] (HELO sctel.ru)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187618316 for klescheva@iph.ru; Mon, 26 May 2003 01:27:25 +0400
Received: from marina (212.16.212.101)
	by sctel.ru with [XMail 1.11 (Win32/Ix86) ESMTP Server]
	id <S314CA> for <klescheva@iph.ru> from <ugs@sctel.ru>;
	Mon, 26 May 2003 08:35:03 +1100
Message-ID: <004801c32304$f06e2ee0$23c8a8c0@marina>
From: =?koi8-r?B?7cHSyc7BIO7P18nDy8HR?= <ugs@sctel.ru>
To: "klescheva" <klescheva@iph.ru>
References: <004c01c3213a$81839590$05180e0a@iph.int>
Subject: (Archive Copy) =?koi8-r?B?8NLP3snUwc7POiD3zsnNwc7JwCD6z8zP1NXIyc7PyiDsLu0u?=
Date: Mon, 26 May 2003 08:30:58 +1100
MIME-Version: 1.0
Content-Type: multipart/report;
	report-type=disposition-notification;
	boundary="----=_NextPart_000_003F_01C32361.21E8A340"
X-Mailer: Microsoft Outlook Express 5.50.4133.2400
X-MimeOLE: Produced By Microsoft MimeOLE V5.50.4133.2400
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

This is a multi-part message in MIME format.

------=_NextPart_000_003F_01C32361.21E8A340
Content-Type: text/plain;
	charset="koi8-r"
Content-Transfer-Encoding: base64

9dfFxM/NzMXOycUgzyDQ0s/e1MXOyckg08/Pwt3FzsnRLCDP1NDSwdfMxc7Oz8fPDQoi88HIwczJ
ziAo5snMycHMIPP1/OspICj8zC4g0M/e1MEpIiA8bG9zZXZhQHNjdGVsLnJ1PiDXIDI0LjA1LjIw
MDMgMTo0OQ0KDQrkwc7O2c0g1dfFxM/NzMXOycXNINXEz9PUz9fF0tHF1NPRLCDe1M8g0M/M1d7B
1MXM2CDP1MvS2cwg08/Pwt3FzsnFINcgMjYuMDUuMjAwMyA4OjMw

------=_NextPart_000_003F_01C32361.21E8A340
Content-Type: message/disposition-notification
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

Final-Recipient: rfc822;klescheva@iph.ru
Original-Message-ID: <004c01c3213a$81839590$05180e0a@iph.int>
Disposition: manual-action/MDN-sent-automatically; displayed

------=_NextPart_000_003F_01C32361.21E8A340--

