Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 08:10:35 +0400
X-Deliver-To: lavrushin@iph.ru
Received: from tofsla.infosys.ru ([213.138.192.178] verified)
  by frontend3.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 2393035 for lavrushin@iph.ru; Mon, 26 May 2003 08:13:38 +0400
Received: from localhost (tty07.infosys.ru [213.138.192.38])
	by tofsla.infosys.ru (8.12.9/8.12.9) with SMTP id h4Q4DUv8023382
	for <lavrushin@iph.ru>; Mon, 26 May 2003 15:13:31 +1100
Received: from boss ([192.168.255.7]) by local with ESMTP id 286 for <lavrushin@iph.ru>; Mon, 26 May 2003 15:11:53 +1100
X-Mail-Server: Eserv/2.99/ннн кНЦХЙЮ
Date: Mon, 26 May 2003 15:07:59 +1100
From: =?koi8-r?B?8/TzIO7ByM/Ey8E=?= <stsnak@stslogistics.com>
X-Mailer: The Bat! (v1.53d)
Reply-To: =?koi8-r?B?8/TzIO7ByM/Ey8E=?= <stsnak@stslogistics.com>
X-Priority: 3 (Normal)
Message-ID: <1417100640.20030526150759@stslogistics.com>
To: =?koi8-r?B?7MHX0tXbyc4g4c7E0sXK?= <lavrushin@iph.ru>
Subject: (Archive Copy) =?koi8-r?B?8sXL18naydTZIMvPzdDBzsnJ?=
MIME-Version: 1.0
Content-Type: text/plain; charset=koi8-r
Content-Transfer-Encoding: 8bit
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru


Андрей,привет!
Дай реквизиты новой фирмы,нам необходимо
уже несколько счетов,ждем от тебя только
отмашки.
Заранее благодарен.

B.RGDS
Руслан.
"STS-Logistics"Nakhodka,Russia
Tel.+7(4236)692-568
Fax.+7(4236)679-734
mailto:stsnak@stslogistics.com
WWW.STSLOGISTICS.COM

