Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 07:26:06 +0400
X-Deliver-To: iph@iph.ru
Received: from [64.8.50.184] (HELO mta4.adelphia.net)
  by frontend2.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187872749 for iph@iph.ru; Mon, 26 May 2003 07:28:43 +0400
Received: from sadfasdf ([68.68.188.61]) by mta4.adelphia.net
          (InterMail vM.5.01.05.32 201-253-122-126-132-20030307) with SMTP
          id <20030526032827.GYDE1051.mta4.adelphia.net@sadfasdf>;
          Sun, 25 May 2003 23:28:27 -0400
Reply-To: cnofeu@tele.net
From: info-net<cnofeu@tele.net>
Subject: (Archive Copy) для предпринимателей, руководителей, в отдел маркетинга
Date: Mon, 26 May 2003 07:17:25 +0400
MIME-Version: 1.0
Content-Type: text/html;
	charset="Windows-1251"
Content-Transfer-Encoding: 7bit
X-Priority: 1
X-MSMail-Priority: High
X-Mailer: Microsoft Outlook Express 6.00.2600.0000
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2600.0000
Message-Id: <20030526032827.GYDE1051.mta4.adelphia.net@sadfasdf>
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

<META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=windows-1251">
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1251">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 10">
<meta name=Originator content="Microsoft Word 10">
<link rel=File-List
href="Предприятия-России-2003+wa2%20registr.files/filelist.xml">
<title>для предпринимателей, руководителей, в отдел маркетинга </title>
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>Slawik</o:Author>
  <o:Template>Normal</o:Template>
  <o:LastAuthor>Slawik</o:LastAuthor>
  <o:Revision>8</o:Revision>
  <o:TotalTime>59</o:TotalTime>
  <o:Created>2003-05-14T08:13:00Z</o:Created>
  <o:LastSaved>2003-05-25T07:29:00Z</o:LastSaved>
  <o:Pages>1</o:Pages>
  <o:Words>284</o:Words>
  <o:Characters>1622</o:Characters>
  <o:Company>wwerwe</o:Company>
  <o:Lines>13</o:Lines>
  <o:Paragraphs>3</o:Paragraphs>
  <o:CharactersWithSpaces>1903</o:CharactersWithSpaces>
  <o:Version>10.2625</o:Version>
 </o:DocumentProperties>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:SpellingState>Clean</w:SpellingState>
  <w:GrammarState>Clean</w:GrammarState>
  <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>
 </w:WordDocument>
</xml><![endif]-->
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:Verdana;
	panose-1:2 11 6 4 3 5 4 4 2 4;
	mso-font-charset:204;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:536871559 0 0 0 415 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-parent:"";
	margin:0cm;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";}
a:link, span.MsoHyperlink
	{color:blue;
	text-decoration:underline;
	text-underline:single;}
a:visited, span.MsoHyperlinkFollowed
	{color:blue;
	text-decoration:underline;
	text-underline:single;}
p
	{mso-margin-top-alt:auto;
	margin-right:0cm;
	mso-margin-bottom-alt:auto;
	margin-left:0cm;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";}
span.SpellE
	{mso-style-name:"";
	mso-spl-e:yes;}
span.GramE
	{mso-style-name:"";
	mso-gram-e:yes;}
@page Section1
	{size:595.3pt 841.9pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;
	mso-header-margin:35.4pt;
	mso-footer-margin:35.4pt;
	mso-paper-source:0;}
div.Section1
	{page:Section1;}
 /* List Definitions */
 @list l0
	{mso-list-id:719592144;
	mso-list-template-ids:-1230596518;}
@list l0:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:36.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
@list l1
	{mso-list-id:883558553;
	mso-list-template-ids:804133260;}
@list l1:level1
	{mso-level-number-format:bullet;
	mso-level-text:\F0B7;
	mso-level-tab-stop:36.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;
	mso-ansi-font-size:10.0pt;
	font-family:Symbol;}
@list l1:level2
	{mso-level-tab-stop:72.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level3
	{mso-level-tab-stop:108.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level4
	{mso-level-tab-stop:144.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level5
	{mso-level-tab-stop:180.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level6
	{mso-level-tab-stop:216.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level7
	{mso-level-tab-stop:252.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level8
	{mso-level-tab-stop:288.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
@list l1:level9
	{mso-level-tab-stop:324.0pt;
	mso-level-number-position:left;
	text-indent:-18.0pt;}
ol
	{margin-bottom:0cm;}
ul
	{margin-bottom:0cm;}
-->
</style>
<!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
	{mso-style-name:"Обычная таблица";
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	mso-style-noshow:yes;
	mso-style-parent:"";
	mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
	mso-para-margin:0cm;
	mso-para-margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:10.0pt;
	font-family:"Times New Roman";}
</style>
<![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="8194"/>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext="edit">
  <o:idmap v:ext="edit" data="1"/>
 </o:shapelayout></xml><![endif]-->
</head>

<body bgcolor="#ECF5FF" lang=RU link=blue vlink=blue style='tab-interval:35.4pt'>

<div class=Section1>

<p class=MsoNormal><b><span style='font-size:10.0pt;font-family:Verdana'>для</span></b><span
style='font-size:10.0pt;font-family:Verdana'> <span style='background:yellow'>предпринимателей</span>,&nbsp;
<span style='background:yellow'>руководителей,</span> <span style='background:
yellow'>в отдел маркетинга</span></span> </p>

<p class=MsoNormal><b><u><span style='font-size:10.0pt;font-family:Verdana'>предлагаем:<o:p></o:p></span></u></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;font-family:Verdana'>Электронный
информационный справочник</span></b><span style='font-size:10.0pt;font-family:
Verdana'><br>
<b>&quot;Предприятия-России-2003&quot;</b>&nbsp;<br>
~590тыс организаций и предприятий <u>по всем</u> регионам России.&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>В
справочнике можно выделить любой сегмент предприятий Российского рынка, найти
спрос и <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>предложение
нужных Вам видов товаров или услуг.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>Вы
сможете:<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>-
проводить рекламные кампании;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>-
находить новых партнеров и клиентов;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>-
исследовать рынок, формировать маркетинговую стратегию своей фирмы;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>- искать
новые направления развития;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>- успешно
реализовывать товар и многое другое.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:Verdana'>&nbsp;<br>
Справочник содержит полную информацию о предприятии:</span> </p>

<table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 align=left
 width=439 style='width:263.4pt;mso-cellspacing:0cm;background:#FFFFAA;
 border:outset black 1.0pt;mso-border-alt:outset black .75pt;mso-table-lspace:
 1.8pt;mso-table-rspace:1.8pt;mso-table-anchor-vertical:paragraph;mso-table-anchor-horizontal:
 column;mso-table-left:left;mso-padding-alt:0cm 0cm 0cm 0cm'>
 <tr style='mso-yfti-irow:0;mso-yfti-lastrow:yes'>
  <td width=58 style='width:34.8pt;border:inset black 1.0pt;mso-border-alt:
  inset black .75pt;padding:0cm 0cm 0cm 0cm'>
  <p class=MsoNormal align=center style='text-align:center;mso-element:frame;
  mso-element-frame-hspace:1.8pt;mso-element-wrap:around;mso-element-anchor-vertical:
  paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly'><span
  style='font-size:7.5pt;font-family:Verdana;background:#FFFFAA'>Название</span></p>
  </td>
  <td width=112 style='width:67.2pt;border:inset black 1.0pt;mso-border-alt:
  inset black .75pt;padding:0cm 0cm 0cm 0cm'>
  <p class=MsoNormal align=center style='text-align:center;mso-element:frame;
  mso-element-frame-hspace:1.8pt;mso-element-wrap:around;mso-element-anchor-vertical:
  paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly'><span
  style='font-size:7.5pt;font-family:Verdana;background:#FFFFAA'>Вид
  Деятельности</span></p>
  </td>
  <td width=79 style='width:47.4pt;border:inset black 1.0pt;mso-border-alt:
  inset black .75pt;padding:0cm 0cm 0cm 0cm'>
  <p class=MsoNormal align=center style='text-align:center;mso-element:frame;
  mso-element-frame-hspace:1.8pt;mso-element-wrap:around;mso-element-anchor-vertical:
  paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly'><span
  class=SpellE><span style='font-size:7.5pt;font-family:Verdana;background:
  #FFFFAA'>Город<span class=GramE>.А</span>дрес</span></span></p>
  </td>
  <td width=93 style='width:55.8pt;border:inset black 1.0pt;mso-border-alt:
  inset black .75pt;padding:0cm 0cm 0cm 0cm'>
  <p class=MsoNormal align=center style='text-align:center;mso-element:frame;
  mso-element-frame-hspace:1.8pt;mso-element-wrap:around;mso-element-anchor-vertical:
  paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly'><span
  style='font-size:7.5pt;font-family:Verdana;background:#FFFFAA'>Телефон/Факс</span></p>
  </td>
  <td width=43 style='width:25.8pt;border:inset black 1.0pt;mso-border-alt:
  inset black .75pt;padding:0cm 0cm 0cm 0cm'>
  <p class=MsoNormal align=center style='text-align:center;mso-element:frame;
  mso-element-frame-hspace:1.8pt;mso-element-wrap:around;mso-element-anchor-vertical:
  paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly'><span
  class=SpellE><span style='font-size:7.5pt;font-family:Verdana;background:
  #FFFFAA'>E-mail</span></span></p>
  </td>
  <td width=40 style='width:24.0pt;border:inset black 1.0pt;mso-border-alt:
  inset black .75pt;padding:0cm 0cm 0cm 0cm'>
  <p class=MsoNormal align=center style='text-align:center;mso-element:frame;
  mso-element-frame-hspace:1.8pt;mso-element-wrap:around;mso-element-anchor-vertical:
  paragraph;mso-element-anchor-horizontal:column;mso-height-rule:exactly'><span
  style='font-size:7.5pt;font-family:Verdana;background:#FFFFAA'>WWW</span></p>
  </td>
 </tr>
</table>

<p class=MsoNormal align=center style='text-align:center'><span lang=EN-US
style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<ul type=disc>
 <li class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
     mso-list:l1 level1 lfo3;tab-stops:list 36.0pt'><span style='font-size:
     7.5pt;font-family:Verdana'>Справочник имеет <span class=GramE>свои</span>
     удобный программный интерфейс на русском языке;<o:p></o:p></span></li>
 <li class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
     mso-list:l1 level1 lfo3;tab-stops:list 36.0pt'><span style='font-size:
     7.5pt;font-family:Verdana'>Поставляется на CD-носителе. подходит для
     любого типа PC;</span></li>
 <li class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
     mso-list:l1 level1 lfo3;tab-stops:list 36.0pt'><span style='font-size:
     7.5pt;font-family:Verdana'>Подробное рубрицирование;</span></li>
 <li class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
     mso-list:l1 level1 lfo3;tab-stops:list 36.0pt'><span style='font-size:
     7.5pt;font-family:Verdana'>Широкие возможности поиска и экспорта;</span></li>
 <li class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
     mso-list:l1 level1 lfo3;tab-stops:list 36.0pt'><span style='font-size:
     7.5pt;font-family:Verdana'>Универсальность;<o:p></o:p></span></li>
 <li class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
     mso-list:l1 level1 lfo3;tab-stops:list 36.0pt'><span style='font-size:
     7.5pt;font-family:Verdana'>Актуальность информации - январь 2003 года;<o:p></o:p></span></li>
</ul>

<p><span style='font-size:10.0pt;font-family:Verdana'>Стоимость справочника
100$.<br>
<b><span style='color:blue'>бесплатная доставка</span></b> по Москве.<o:p></o:p></span></p>

<p><span style='font-size:10.0pt;font-family:Verdana'>Если Вы закажете этот
справочник у нас, то Вы <b style='mso-bidi-font-weight:normal'><span
style='color:red'>БЕСПЛАТНО</span></b> получите справочник крупных предприятий
России </span><b style='mso-bidi-font-weight:normal'><span lang=EN-US
style='font-size:10.0pt;font-family:Verdana;color:red;mso-ansi-language:EN-US'>WA</span></b><b
style='mso-bidi-font-weight:normal'><span style='font-size:10.0pt;font-family:
Verdana;color:red'>-2 </span></b><b style='mso-bidi-font-weight:normal'><span
lang=EN-US style='font-size:10.0pt;font-family:Verdana;color:red;mso-ansi-language:
EN-US'>REGISTR</span></b><span lang=EN-US style='font-size:10.0pt;font-family:
Verdana;color:red'> </span><span style='font-size:10.0pt;font-family:Verdana'>в
формате </span><span lang=EN-US style='font-size:10.0pt;font-family:Verdana;
mso-ansi-language:EN-US'>Excel</span><span style='font-size:10.0pt;font-family:
Verdana'>. <span class=GramE>В базе 11.000 предприятий, имеются следующие поля:
название, организационная форма, год основания, регион, индекс, адрес,
численность работающих, почтовый адрес, имя директора, контактный телефон, <span
lang=EN-US style='mso-ansi-language:EN-US'>e</span>-<span lang=EN-US
style='mso-ansi-language:EN-US'>mail</span>, <span lang=EN-US style='mso-ansi-language:
EN-US'>www</span>, полная информация по </span>предоставляемым услугам и
выпускаемой продукции.<span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>

<p align=center style='text-align:center'><b style='mso-bidi-font-weight:normal'><span
style='font-family:Verdana'>Уникальное предложение!!!</span></b><span
style='font-family:Verdana'> <b style='mso-bidi-font-weight:normal'>Вы
покупаете две базы данных по цене одной!!!</b><o:p></o:p></span></p>

<p><b style='mso-bidi-font-weight:normal'><span style='font-size:10.0pt;
font-family:Verdana;color:red'>(!)</span></b><span style='font-size:10.0pt;
font-family:Verdana'> Если Вы <span class=GramE>сделаете заказ до <b
style='mso-bidi-font-weight:normal'><span style='color:red'>15.06.03</span></b><span
style='color:red'> </span>Вы получите</span> в <b style='mso-bidi-font-weight:
normal'><span style='color:red'>ПОДАРОК</span></b> уникальный комплекс программ
для массовых </span><span lang=EN-US style='font-size:10.0pt;font-family:Verdana;
mso-ansi-language:EN-US'>e</span><span style='font-size:10.0pt;font-family:
Verdana'>-</span><span lang=EN-US style='font-size:10.0pt;font-family:Verdana;
mso-ansi-language:EN-US'>mail</span><span lang=EN-US style='font-size:10.0pt;
font-family:Verdana'> </span><span style='font-size:10.0pt;font-family:Verdana'>рассылок
+ программу для поиска </span><span lang=EN-US style='font-size:10.0pt;
font-family:Verdana;mso-ansi-language:EN-US'>e</span><span style='font-size:
10.0pt;font-family:Verdana'>-</span><span lang=EN-US style='font-size:10.0pt;
font-family:Verdana;mso-ansi-language:EN-US'>mail</span><span lang=EN-US
style='font-size:10.0pt;font-family:Verdana'> </span><span style='font-size:
10.0pt;font-family:Verdana'>адресов по ключевым словам!!!<br>
<b>Для заказа <a href="mailto:sbase@seznam.cz"><span class=GramE>пишите</span></a>
оставляйте свой контактный телефон. Оплата наличными курьеру, либо наложенным
платежом.</b><o:p></o:p></span></p>

<p><span class=GramE><span lang=EN-US style='font-size:8.0pt;font-family:Verdana;
mso-ansi-language:EN-US'>P</span><span style='font-size:8.0pt;font-family:Verdana'>.</span><span
lang=EN-US style='font-size:8.0pt;font-family:Verdana;mso-ansi-language:EN-US'>S</span><span
style='font-size:8.0pt;font-family:Verdana'>. Заранее приносим извинения, если
данное предложение доставило Вам некоторые неудобства.</span></span><span
style='font-size:8.0pt;font-family:Verdana'><o:p></o:p></span></p>

</div>

</body>

</html>
