Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 03:58:06 +0400
X-Deliver-To: iph@iph.ru
Received: from [211.225.111.221] (HELO microsoft.com)
  by frontend2.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with SMTP id 187854916 for iph@iph.ru; Mon, 26 May 2003 04:01:02 +0400
Date: Mon, 26 May 2003 08:01:29 +0000
From: Boom20 <boom20@msn.com>
Subject: (Archive Copy) —адовые формы, пиломатериалы 61649
To: Iph <iph@iph.ru>
References: <2EC3FGJ80B26CF0F@iph.ru>
In-Reply-To: <2EC3FGJ80B26CF0F@iph.ru>
Message-ID: <15K6CKELLKEBGE0I@msn.com>
Reply-To: Baz04 <baz04@msn.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=Windows-1251
Content-Transfer-Encoding: 8bit
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

iph@iph.ru

ƒеревообрабатывающий завод Ќико производит высококачественные садовые архитектурные формы: решетки, беседки, заборы, перголы из элитного материала. –аботаем по индивидуальным проектам.

Ћиственница - лучший выбор дл€ создани€ садовых композиций, которые €вл€ютс€ прекрасным обустройством вашего сада.

“ак же предлагаем вашему вниманию материалы дл€ внутренней отделки: вагонка, доска пола из лиственницы высшей категории.

тел. (095) 549-41-50, (095) 549-41-49

MjaElObgXJGeeXY

