Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 02:06:32 +0400
X-Deliver-To: iph@iph.ru
Received: from tomts6-srv.bellnexxia.net ([209.226.175.26] verified)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187623242 for iph@iph.ru; Mon, 26 May 2003 02:09:09 +0400
Received: from americsa ([67.68.187.248]) by tomts6-srv.bellnexxia.net
          (InterMail vM.5.01.05.32 201-253-122-126-132-20030307) with SMTP
          id <20030525220907.QUSA17633.tomts6-srv.bellnexxia.net@americsa>;
          Sun, 25 May 2003 18:09:07 -0400
Reply-To: wyobuu@microsoft.com
From: Шевыров Николай<wyobuu@microsoft.com>
Subject: (Archive Copy) Управление персоналом. Тренинг
Date: Mon, 26 May 2003 02:08:55 +0400
MIME-Version: 1.0
Content-Type: text/html;
	charset="Windows-1251"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2800.1081
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1081
Message-Id: <20030525220907.QUSA17633.tomts6-srv.bellnexxia.net@americsa>
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1251">
<META NAME="Generator" CONTENT="Microsoft Word 97">
<TITLE>УПРАВЛЕНИЕ ПЕРСОНАЛОМ</TITLE>
</HEAD>
<BODY LINK="#0000ff" VLINK="#800080">

<P ALIGN="CENTER"></P>
<B><FONT FACE="Arial"><P>УПРАВЛЕНИЕ ПЕРСОНАЛОМ</P>
</B><P>31 мая -1 июня 2003 года                            Инна Чинилина</P>

<B><U><P>Программа рассчитана</B></U> на руководителей компаний, руководителей отделов и рабочих групп.</P>

<B><U><P>В программе:</P>
</U></FONT><P>Стратегии организационного развития.</B> Организационная культура.</P>
<B><P>Мотивация персонала</B>. Способы и методы нематериального мотивирования.</P>
<B><P>Управление конфликтами.</B> Алгоритм разрешения. Приемы сохранения авторитета руководителя. Способы предъявления претензий сотрудникам и критики подчиненных</P>
<B><P>Совещания:</B> цели, форматы, эффективность.</P>
<B><P>Таймменеджмент</B>: управление своим временем и временем подчиненных.</P>
<B><P>Функции менеджмента.</P>
<P>Стили руководства.</B> Управленческие решения.</P>
<B><P>Планирование.</B> Стратегические и оперативные цели. Алгоритм эффективной постановки задачи сотрудникам.</P>
<B><P>Контроль.</B> Виды и способы. Обратная связь. Планирование контрольных мероприятий. Критерии результативности.</P>
<B><P>Делегирование полномочий</B>, как способ экономии собственного времени. Возможности и границы.</P>

<B><U><P>Заявку на участие</U> </B>Вы можете отправить <B>до 28 мая </B>по электронной почте:<B> </B><A HREF="mailto:igor@ruseller.ru">igor@ruseller.ru</A><B> </P>
</B><P>или по телефону: <B>933-71-81 доб. 340, 359, 358, 257, 622</P>
</B><P>&nbsp;С уважением, Шевыров Николай</P>
<P>Консалтинговая компания "АРИКА"</P>
<P>&nbsp;&nbsp;</P>
<P>График открытых тренингов: <B>май-июнь</P></B>
<TABLE BORDER CELLSPACING=5 CELLPADDING=7 WIDTH=538>
<TR><TD WIDTH="21%" VALIGN="MIDDLE">
<FONT SIZE=3><P ALIGN="CENTER">Дата проведения</FONT></TD>
<TD WIDTH="51%" VALIGN="MIDDLE">
<FONT SIZE=3><P ALIGN="CENTER">Название программы</FONT></TD>
<TD WIDTH="28%" VALIGN="MIDDLE">
<FONT SIZE=3><P ALIGN="CENTER">Тренер</FONT></TD>
</TR>
<TR><TD WIDTH="21%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">31 мая-1 июня</FONT></TD>
<TD WIDTH="51%" VALIGN="MIDDLE" HEIGHT=35>
<B><P ALIGN="CENTER">Управление персоналом</B></TD>
<TD WIDTH="28%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">Инна Чинилина</FONT></TD>
</TR>
<TR><TD WIDTH="21%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">7-8 июня</FONT></TD>
<TD WIDTH="51%" VALIGN="MIDDLE" HEIGHT=35>
<B><FONT SIZE=3><P ALIGN="CENTER">Стратегии и тактики работы с клиентом.</B></FONT></TD>
<TD WIDTH="28%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">Елена Ревенко</FONT></TD>
</TR>
<TR><TD WIDTH="21%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">21-22 июня</FONT></TD>
<TD WIDTH="51%" VALIGN="MIDDLE" HEIGHT=35>
<B><FONT SIZE=3><P ALIGN="CENTER">Телемаркетинг</B></FONT></TD>
<TD WIDTH="28%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">Инна Чинилина</FONT></TD>
</TR>
<TR><TD WIDTH="21%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">28-29 июня </FONT></TD>
<TD WIDTH="51%" VALIGN="MIDDLE" HEIGHT=35>
<B><FONT SIZE=3><P ALIGN="CENTER">Легкая работа с трудными клиентами</B></FONT></TD>
<TD WIDTH="28%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">Елена Ревенко</FONT></TD>
</TR>
<TR><TD WIDTH="21%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">5-6 Июля</FONT></TD>
<TD WIDTH="51%" VALIGN="MIDDLE" HEIGHT=35>
<B><FONT SIZE=3><P ALIGN="CENTER">Публичное выступление</B></FONT></TD>
<TD WIDTH="28%" VALIGN="MIDDLE" HEIGHT=35>
<FONT SIZE=3><P ALIGN="CENTER">Овчинников Евгений</FONT></TD>
</TR>
</TABLE>

</BODY>
</HTML>

