Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 08:06:11 +0400
X-Deliver-To: goncharova@iph.ru
Received: from cat233.subscribe.ru ([81.9.34.233] verified)
  by frontend2.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187875387 for goncharova@iph.ru; Mon, 26 May 2003 08:08:45 +0400
X-Felis-Deliver-Id: 251A61AEEF1D; Mon, 26 May 2003 08:05:11 +0400
X-Felis-Queue-Id: 20030526080501
Message-Id: <20030526080724_hk_=3405====n==t_@culture.fil2000.subscribe>
Precedence: normal
List-Id: <culture.fil2000.subscribe.ru>
List-Help: <mailto:ask@subscribe.ru>
List-Owner: <mailto:ask@subscribe.ru>
List-Subscribe: <http://Subscribe.Ru/catalog/culture.fil2000>
List-Unsubscribe: <http://Subscribe.Ru/catalog/culture.fil2000>
List-Archive:  <http://Subscribe.Ru/archive/culture.fil2000>
List-Post: NO
Date: Mon, 26 May 2003 08:07:13 +0400
From: Subscribe.Ru <namma397137@subscribe.ru>
To: "culture.fil2000" <goncharova@iph.ru> (397137)
Subject: (Archive Copy) =?koi8-r?Q?=F6=C5=CD=DE=D5=D6=C9=CE=D9=20=CD=D5=C4=D2=CF=D3=D4=C9.=20?=
 =?koi8-r?Q?=E6=D2=C1=DA=C1=20=CE=C1=20=CB=C1=D6=C4=D9=CA=20?=
 =?koi8-r?Q?=C4=C5=CE=D8"?=
MIME-Version: 1.0
Content-Type: multipart/related;
  boundary="=felis-related=20030526080720=28783";
  type=text/html
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

This is MIME letter


--=felis-related=20030526080720=28783
Content-Language: ru
Content-Type: text/html; charset=koi8-r
Content-Transfer-Encoding: 8bit


<!--
--*--
-->
<HTML lang="ru"><HEAD> 
<TITLE>Subscribe.Ru : Жемчужины мудрости. Фраза на каждый день"</TITLE> 
<META NAME="keywords" CONTENT="Философия психология культура искусство этика мудрость творчество"> 
<META NAME="author" CONTENT="karelin@atanor.ru Ведущий рассылки Вадим Карелин"> 
<STYLE><!--  --></STYLE> 
</HEAD><BODY bgcolor=#D1E6BD><IMG SRC=http://image.subscribe.ru/1.gif/culture.fil2000/20030526080713/=3405====n==t/m397137 HEIGHT=1 WIDTH=1><!--#include virtual="/archive/header.issue.shtml"--> 
<!--noindex--> 
<CENTER> 
<table style="background-color: #d1e6bd; background-image: ;" background="" bgcolor="#d1e6bd" width="100%" cellpadding="7" cellspacing="0" border="0"><tr> 
<td align="center" width=100%><B><font SIZE=2 color=#000000 style="color: #000000; font-size: 10pt;">Информационный Канал</font> 
<A TARGET=_top HREF=http://subscribe.ru/><font SIZE=2 color="#000000" style="color: #000000; font-size: 10pt;">Subscribe.Ru</font></A></B></td> 
<td align=right><nobr><font SIZE=2 color=#000000 style="color: #000000; font-size: 10pt;"></font></nobr></td> 
</tr></table> 
<HR NOSHADE> 
</CENTER> 
<!--/noindex--> 
<!--noindex-->
<!-- 3405 --><center>
<script language=JavaScript>
<!--
var seed=Math.round(Math.random()*65535);
document.write("<img src=http://engine.awaps.net/0/2687/001001.gif?0-0-"+seed+"-0-a:8207p:7367 width=1 height=1 border=0>");
//-->
</script>
<noscript>
<img src=http://engine.awaps.net/0/2687/001001.gif?0-0-0-0-a:8207p:7367 width=1 height=1 border=0>
</noscript>
<table border=0 cellpadding=0 cellspacing=0>
<tr><td>
<a href="http://link.subscribe.ru/5623/397137"><img src="cid:advert/adwatch/030512megafon.gif" width=500 height=100 border=0></a></td></tr>
<tr><td align=right><font size=1>Реклама</font></td></tr>
</table>
</center>
<HR NOSHADE>

<!--/noindex-->












<xbody bgcolor="#D1E6BD">
<p align="center"><img src="http://www.newacropol.ru/img/perl.gif" >
<p align="center">&#160;
<table width="57%" bgcolor="black" border="0" align="center" cellpadding="10" cellspacing="0">
  <tr>

    <td align="justify" bgcolor="#EEF4DD">
      <div align="center"><font face="Arial" size="+1" color="#660000"> <u><b>Фраза
        на день</b></u></font></div>
      <div align="center"><br>
        <font face="Arial">
Мудрец избегает всякой крайности.


</font><br>
       </div>
      <i><font size="2">
      <div align="right"><font face="Arial">Лао-цзы


   </font>
      </div>
      </font></i> </td>
 </tr>
</table>



<table width="57%" border="0" align="center" cellpadding="10" cellspacing="0">
  <tr>

    <td align="justify">
      <div align="center">
        <p><font face="Arial" size="+1" color="#660000"><u>Цитаты:</u></font>
        </p>
        </div>

      <br>
      <font face="Arial">Когда боишься&#160;&mdash; действуй смело,
И ты избегнешь худших бед.


</font><br>
          <i><font size="2">
      <div align="right"><font face="Arial">Ганс Сакс



  </font> </div>

</font></i> <br>
          <br>
      <font face="Arial">
Очевидное&#160;&mdash; это то, чего никто не видит, пока кто-нибудь не выразит его наипростейшим способом.

   </font> <br>
          <i><font size="2">
      <div align="right"><font face="Arial">
Джебран Халиль Джебран


   </font>
      </div>

      </font></i> <br>
        <br>
        <font face="Arial"> Высшая мудрость&#160;&mdash; философствуя, не казаться философствующим и шуткой достигать серьезной цели.


 </font><br>

      <i><font size="2">
<div align="right"><font face="Arial">Плутарх











        </font></div>


</font></i><br>
    </td>
 </tr>

  <tr>

    <td align="left"  bgcolor="#EEF4DD">
      <p><font face="Arial">Читайте на сайте "Нового Акрополя": <a href="http://philosophy.newacropol.ru/philosophy/index.php?file=article/1_16.htm"  target="_blank" style="text-decoration:none"> "Что такое "быть человеком"</a></font>
      <p><font face="Arial">Читайте на сайте журнала "Новый
        Акрополь": <a href="http://journal.newacropol.ru/4_2002/articles/106.php"  target="_blank" style="text-decoration:none">"Любечский замок" </a></font></p>
    </td>
 </tr>
</table>

<br>
<table width="57%" border="0" align="center" cellpadding="10" cellspacing="0">
  <tr>

    <td align="center"> <font face="Arial" size="+1" color="#13694E"> <i><a href="http://www.newacropol.ru" target="_self">Новости
      &laquo;Нового Акрополя&raquo; </a></i></font><font face="Arial" size="+2" color="Black"><i></i></font><font face="Arial" size="+1" color="#13694E"><i><a href="http://www.newacropol.ru" target="_self"></a></i></font>
      <br>

 </td>
 </tr>
</table>

<p align="center">
<a href="http://www.newacropol.ru" target=_blank><img align="center" src="http://www.newacropol.ru/img/lections.gif" width="480" height="60"></a>
<br>
<br>

<table width="75%" bgcolor="black" border="0" align="center" cellpadding="5" cellspacing="0">
  <tr>

    <td align="center" bgcolor="#EEF4DD"> <a href="http://www.newacropol.ru" target="_self">www.newacropol.ru</a><br>
      <a href="mailto:info@newacropol.ru">info@newacropol.ru</a> </td>
 </tr>
</table>







<!--noindex-->
<!-- t --><hr>

<center>
<table border=0 cellpadding=0 cellspacing=0 width=80%><tr><td align=center>
<table
style="FONT-FAMILY: arial; background-color: white;" bgcolor="white"
border=1 cellpadding=0 cellspacing=0><tr><td>
<table border=0 cellpadding=3 cellspacing=0>
<tr>

<td>
<a href="http://subscribe.ru/catalog/comp.soft.linux.lcnews"><font style="color: black; text-decoration: none" color=black size=3><b>LinuxCenter News Channel: новости Linux</b>.</font><br>
<font style="color: black; text-decoration: none" color=black size=2>
Информационный канал Линукс Центра, где публикуются последние новости о самых важных событиях, связанных с Linux, а также информация о выходе свежих версий программного обеспечения и дистрибутивов.
</font>
</a>
<table border=0 cellspacing=0 cellpadding=0 width=100%><tr>
<td width=40% align=left><b><a href="http://subscribe.ru/catalog/comp.soft.linux.lcnews"><font style="color: black;" color=black size=2>Подписаться</font></a></b>.</td>
<td width=10%>&nbsp;</td>
<td width=50% align=right valign=bottom><nobr>
<a href="http://subscribe.ru/catalog"><font style="color: black;" color=black size=1>Рассылки Subscribe.Ru</font></a>
</nobr></td>
</tr></table>

</td></tr></table>
</td></tr></table>
</td></tr></table>
</center>
<HR NOSHADE><CENTER>
<iframe src="http://ad.adriver.ru/cgi-bin/erle.cgi?sid=458?bt=1?pz=3?sz=/culture.lit.quotation?rnd=366625305" frameborder=0 vspace=0 hspace=0 width=468 height=60 marginwidth=0 marginheight=0 scrolling=no><a target=_top href="http://ad.adriver.ru/cgi-bin/click.cgi?sid=458?bt=1?pz=3?sz=/culture.lit.quotation?rnd=366625305"><img src="http://ad.adriver.ru/cgi-bin/rle.cgi?sid=458?bt=1?pz=3?sz=/culture.lit.quotation?rnd=366625305" alt="-AdRiver-" border=0 width=468 height=60></a></iframe>
</CENTER>
<CENTER><HR NOSHADE><TABLE style="background-color: #d1e6bd; background-image: ;" background="" bgcolor="#d1e6bd" cellpadding="7" cellspacing="0" BORDER=0 WIDTH=100%><TR> 
<TD ALIGN=left valign=top><A TARGET=_top HREF=http://subscribe.ru/><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">http://subscribe.ru/</font></A> 
<BR><font size=2 color=#000000 style="color: #000000; font-size: 10pt;">E-mail:</font> <A HREF=mailto:ask@subscribe.ru><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">ask@subscribe.ru</font></A> 
</TD><TD ALIGN=right valign=top> 
<A TARGET=_top HREF=http://subscribe.ru/member/unsub?grp=culture.fil2000&email=goncharova@iph.ru><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">Отписаться</font></A> 
<br><A TARGET=_top HREF=http://link.subscribe.ru/noad><font size=2 color="#000000" style="color: #000000; font-size: 10pt;">Убрать рекламу</font></A> 
</TD></TR></TABLE></CENTER> 
<!--#include virtual="/archive/footer.issue.shtml"--></BODY></HTML> 
<!--/noindex-->


--=felis-related=20030526080720=28783
Content-Type: image/gif;
  name=_adwatch/030512megafon.gif
Content-Transfer-Encoding: base64
Content-Location: advert/adwatch/030512megafon.gif
Content-ID: <advert/adwatch/030512megafon.gif>

R0lGODlh9AFkAMQAAPbz9ioCYfbQAQSaBF85irEFPn5fo5fXl6+Zxt+mF7+v0cfpxXgGV2XDZfvs
mN7S5JqCt+zi7fKdrS+xMvjcSM/C2+puE3FaXun13+pdduMqNKqIOz4Qe94BKf///73reiwAAAAA
9AFkAAAF/2AnjmRpnmiqrmzbcTBXlHFtx0xZ2F7vfcCgcEgsGo/IpHLJbDqf0Kh0Sq1ar1ina8vt
elm1GWl3K5tuvl92zW673/C4fE5nfu/4vCpsYpRrOTpoPnWFhoeIiYqLcnqOj3eAJwV+NgwMYjQ2
BGmMnp+goaKjVpCmpyuVMI5lnISksLGys7RwqLe4IqoyebsxBp21wsPExcO5yKZkMXh/HAjBxtJS
MYkcVddG2dPcyd6Ovl7LNwQR0UvbH+ncs+uG29VAMEHz6vXy2kLxQ/v4VP37+vkz9q3gnXEwMq1A
eAPaOSXw3LEjJbEOPHryIqrDyFFftYv6OAp8AvIiyIzTuv9QwoRp0iUOLy8F6nBpJaZMBVbqHLES
pp+aX3zBzDmJkrMYBACkUWNkhMiNGe9FnEpvXrarHqnyQxk1arqPNaDWA3gvq72vYwP60wp148mR
JzFem9t2a8i3dutWjDcyZFu6AwFnnVuWb9k5XRgQMMCYg4kCAQhAQKCgMgIDQwssZsyYwEzFnBvP
8COZcmUIBALM5FKDwIUNCRIImB17wwUCR2tUWMq0iNO1Yu92xIrVLfDAf7d+lfv0uHHkyf1GN9m8
eEnm9qB3PMscsEB3UrdHH6h8fF7qx8EPxy4+joucfhT0qOB4DAcIEZT6AABAgWfN/AUIAS87QBAg
ABEQYJT/AvqlAQACMInDwQWxzWbhhbTZlptDSyHx23PFbXcdVdZVBdZ3hbEX4orhrRWWdNfhE6N1
L9pg3FUvthfcjiIWMZZ4ce31XF09yihSjtqhh2QjC1VigHw9PNDSCBwY0CB/+ykAU1JpPEAgBw84
6NkzV145oEItaCAbhmxemMAGuJUBAW89ONHicnitCKJ25NmVZ3M8lugcEXglN+OgyP1IJIzVGUme
RHT9+aiPji66DnpEqgcdcYDaksozDzToAX327TafAQQg0GBqVi5lQA4MtOpDgoqZ48GDjHHo5Wos
WLBmm8DSdsENBtLZG0QwqtXVDcH9YSKOh72VVmEtTkft/2HckcWWs2fpKW20ZvUJbV5emehXQEgy
C1eO6GoqHXfdWsUXYgtxwGB+PkiJEwemAmBAAAAbUMHA/3KZBgIB7MBhD7Qa/EBqATwzsH+8pqCB
BcFmfOEGSC3M2zvvHlERNhP1mcXIduYjMhTLgdIyIizsQMDMc85Xnwg7mDoqqhxEHPElrqSRYGRh
Cu1ZOT4gMHPPEQ/Vgq8aR03bYjobW/IUKF9tRdbIqqz1MTHDB0yUU+pScw8APFDBZQkByNu/Yxvt
R9VpK6C00y1IrbcACYhq9deABy44O1zE6gOpJMzt960PYKZYvqZqCWUFRSdICQFFLwVABbihecKv
e2tMgf+xDw1u+umof1J43PqO4ceToWqOm8EKFBuBAWH6a6rlZEBQga1d4rYCxhgmcMFtxxOwQegC
OEB6nalHL/309LpguM2uMwAwBzRX0KACkR2O+a22cr67Z5dsvxgEmXsAQQAqaNBmAjcsz/zzx1I/
UV/693/F6vkqm2LspoB/veRs9HHYM5YCocqxioCpeQmUPAAhFRAPQxyzAehsY5vXUIhNoyOdnfjn
P0RwrYRRkMoJVzaLwhVrVDejSdwSBJMAxC2B+arSlTDjwABwiD7a82HSYliCC2JwExhKTQwiBiwM
iLAJK0ThHKIoRShqJIVLEgUAyZYJxWTuAQiYDPDe5zD/3HwRBj2UlQceAAEIMAht/0oB6C40rCXa
z0K3mdnM7oihENLJQyLQUbvi1S1z2QhTf8HWvAKjQhI5pyTYgleSppWnRW5KOOIajqISCS20jItQ
0yJkXG4klkYS5lCSHCUdXJhD+6iRN17SIcNSczYyFg0AY/IYAyN0AvkBS4kx4OP9/taUQJYrUYwK
EaAQqadzVWpEwBFUKc2zqOxsUjA02tHLlMmp8ySKMMh8JI8mJc7sCCdSnWrUkJppiNVFID/0UQhk
BOa3/qCvHO/knA1DRSt+IehhlAgA+3gTAQhVbAS+bNMGFsrBOYbuicXswHpEmUxGXjMsi7RRuMjZ
LEOK/zNSS4LUnp5pJO90hZDwUiVKqeMdjC5TkiKqUXf8JCOZPis91iKhp97DPT1WjAyMaSMEeHaT
ns4ME0aVgVE71wGgCnWouDnoCIzIvIcSEx3p3KY2X+ook6qsm4ZCpjR/NDKRenWdXPEqWEsE1omy
dJzTwc6lQpbITHbUmxa9ZjjroJKc+BUFPZFJ2fz6V8LOwLAKEaxgPVcC0CXAAr6C2t4eG9k5QhQd
2hrXFTnJzlPmlR96XdYha8qsnIInRRY1FyOP1Mx5jfJbk5TXtU4K2k4miVyl3GQhQ6asIa3SIMBF
Aeg0QIKESs0CxcXQZavIUSRQkbl0hS6T8KAKqQZXBf+gK2LotHuh5Ur3u3J4LnincJD0CcyAROGJ
YsvWJMUytqmEFe6FiIvQvdF3BJa96nj3y9+USEgyCggTGB0nBtI81XH1qpJQidqHpKLAiPcVAVWB
FeEOGHc23u2vhjccCwnhjk4UowmZhOYfIrqOAG+c1YBmElBV9cfEEp6vCSRbvMdW+MIY1i+Hd8xj
T3jBi2gzB75e7AcOYakHWpIqkNGmHwCc6SUjXiOMLXwh5FpMA1iucH3blOEee/nL1VPveikxmrH5
y0BtRBur9HM7AuhsQJNY4HwWYytaMcCNwIMhCoybgDyoqU1+/BhJIjk9jZJFR2BOtG9owJkFMwZW
NYv/gA39Za/KpIZD/4pM+XhRglpFyTMCTZr2Jni4KXfAiFb2Ao4tFOgOpcxkhcZrWxVN60WTAExN
9oECWGLmNL8PBpUompdyYi81e+56FJSBYvRDH+4FtdQWw5CWWbBqCzlRx0L4kLs+6ZUTYfOk2wSX
izyp1dq2tlKgTMumFBVKvMJ03d+GqWEE1VlFzvtItHVpRTV5qROFa0bxbsIZDNBGBBg8jK+iyfjQ
NirUqEYzmx6NQ/xVsTv7AAI50Iyw/3OJG5q6A45NNbUnfKFWuzqi7XktR7vJbr3wSeXmUamKquKW
bbvcnCYVKaNwi6NMBWqmW9UmO6P5FJ3Pmpl8kute/9fKFYF3mmkAi7pqRMC9PDNsQFXHHk3OlvBO
vxDjTQXTLMVQAFkhbs9ztLGWsQxZh/bx2tgOgrZ9NG9uFh1E7e5kvymZ2mpSSuXK5OQ5u3qtvZuy
PIKZaFhTitOWfoek8s5oKjHK7pBy2yQ1Ck/ilzDwoBKcM4HonQKsDj6keWDX8OF6xWuZcTePXRdm
/ziVgRWb2rs9WM57HkmAFFe34pzoI3Vu7+9qqZljcq6PZDlO7fpzj6A7+PQOes/h6kxUHmqsd82a
Wo2fTb8f4Qy3vNV8WOKHqM+JMnBceDxfMPGuJ+7rrd94gT3eq6pqLPe6H7Sm2GWVpYP7ooRmW902
dP+q9W6bNRjLpC6shXycJWv9N24DSCMK+FluVS22hXmVxCKFF3nnBnlOd2uTQRkieBlIFYJw4wE8
1AMDImy8UGy3oiCIhWwVtGw2Q3ax1wK3Z38m90e1BjKI5jLRRSg9aAedtl4yQWxFAz7AgBm28j7t
pxoLtyuKoUdbYiu7IlD6UUGwB23UZn+Ahj+vMIRiOIZECFg4A4IXBw2T4QNww2wzwyEYpxnewx9j
MkFK82EecDufcYNpkoN6QwFwhz9kOIiEaGtbsGTi9z0w4YKMk0NIdUsK4mlRAjwIgxP0twXVFjWA
CIalU4ieOIRfwD3eozkGJWIpJj714WZKgUvEhof/+1GKIxArWHJ2LZABEeAAoUMB+MeJ0POJvgiK
4vA6AnN6RFVgVWJwdkNgYScZ+aEgTRUxBiCCqMFLPLEZPLMFGVA0GOAAFCA6DrA4nFhr4tUG43g6
5Tg9BxFQBnA7D6cDMuETqwEDc2I56gWP7IUzZHYTLpCNvLGNFPCPAOkADhCIvNiJIqNRKHSOWKCQ
b4CQFrFheiAznGaGj+F6ycZY74UH/FiQHBl3QDB3Pyg9DEkysDCS/6BhjvBXEhJgsOgNG9mRMGmQ
H2lMNzd5nzR9TLcs/FaAK8V38GaB0wRut2WA+1Zz/nZM2nJMN5VuQvl7aJVvKHldroMqflAQthiT
/1gZhrZWJEhXUtW3HgGndLgFeT0Xfdbkd2dVlsw3TYUSI8EnlpTyLm91d/7XX1J5lyKgARJgdVnZ
ka/2UYPhWUXHLkZ5eO+mFx9xd9tHSijygHP5eDOFkHr3TeRGfbz3LIIZTYQpc9CFl1Kpl+DYlwX5
lz/3MoMSWjkJTe4Wb2SVHsoXTld0dM73lNSnJLDpbs01TqiZdODlmcGVARIgmqJJmtvCd0FCmYRZ
LoGHmLLVlslJm5RnSWe1cuMxFQKYWarUF3UXc8ipW+PlmwWhAVcpnH0JhF7jfVsDRWsgXiYJa59Q
VpjUX9MGnqYAmuQ5nO+Zn0zQnid5Bfy5nuq5Yf8SkAH0iQsveZ9Z+YsKWmtpIwHzWaCqtpcIKpwL
WqFghjYD+qAQSm3jOaH4aaEgymFCM6Ab2gXiKQGh6aF+WTKcGaKjoFM+iJ5tAEskWqIrcKJ8qaJY
OUKEpggwOoY/ap4v2qNvQCcNmgEaWqA4qqMISpouKqT/6QZRWjLPEwEZaqMikAEZMIpM2qTfR5OQ
0kiiNEijhW4EmFKZJ6aq1S7fdkiHJyR9B1u7RVtCeBfRmVt1d5RyWltKyXhxKhd3ipNAGZhz6m2J
5w5guDlXSp8n2j5dep+AJFFK2ZVvWU6+1X1g+VJ/cn1N14Gb53s15ZS02RG/wYB213yXhJM/yJr/
3Gd8ulmdLuJNyzl0iMqLDzCgSPqZJyqhj6qikVqBiZmpDchZgskppjp8p6R5K+WVkCR56yKdpERR
FPgBpSprzsSdQul49vaApZmmzemWqaSYskqBWlGrHGmlWopl3oBlwCkBjtqrE/qXgadV2AerLDev
rfp8xDeYl0RT+AqY04mscgemXAlaihdXLec1rEqWq0lOrfWvI+WWs/YBWRkBt5quSYqJ7CoB7pqj
8BqvVrSB2UJz5AqWCWspqMmm8ZKsi1edwWqUdSp4LtucCHiQpjqoOtmUw1qzSTmzAedIEJh0m2Wd
fzoE5IkgFYCrSKqu1MauWsqx+PKxHwtd2heE/8Qwpef5pEWAoAFipUq7tFmWZVr6tFCboqLJOSiW
bAsHr1TbP1gbl1prBFI7t6QDIQuEde/KpHG7t9BFt367FAOCOZT2So/Kt4aLQn+buBgARruxOQqw
AEfWqwtwuJRLPYnrtwcwAQegOZm7AB+LAZUbuqlzuXMLAA0wABPguT2AAaebulI7uaIbu4FDunN7
AAOAug1wAA1wugOwuVILurIbvFdDu7/Lu7d7u5rrt8ArvMwrDcRbvBMQvZqrusoLu817vbXAixFg
N2EUYLxRN2FEGcCTNpTzO0sRAeUbOx6AAQvQvu77vgTJvu0rKu2LAQAgv06Ev/L7vvy7ABjAvv+R
m5Xsi70EHAtgWFBxghQvlIfTWAPDOCpUuMCNwz1VUjSZi7qoOwEYnLw+gAHRi7rUuwAa7Lod3Lq7
u8EjPMID0AALcAAu7LvP28EC2Y2aKJAEGcM4nMM6vMM8TDoT/AfF8sPkECZYBwNqZLdGvIrGe7xM
TL0eYLvHC8NQTMI9sADHu8RMzMQNwL662wA4DADc6IUCoIs33MNmfMaJa7Zo3KUPAwOLQRkNjGuY
wT1uxDYwoCpznMRwVAM148HI2wATAMjIG8IafMU+wLtbnAZTrLuB/MG3C8iAfAD/28IwTLr+KMYl
N5BrvMmczKQLAMipW0Ck1skqejtufIpIjAD/zeaKNHQfprw0sqIlFCxnVgzC98u6j9wgWNwASuHH
K7wUvJu693u/hbzF/+tEaly6YYzJILSLpPzM0MyJuBzF7xMZoxzNomm3FrkfqBGNWHc2SMYYAzM7
mNEqgxsnFpzLaFPMPlDLgYy8TlTLvesgiJwGIny7TpzDy8zMwKKL2PzPAF3FWdy7CBN1uhTQ5xon
4Lwf70Rp3KPKZZJsCiZLCXQ3plfPVVzIvjvNB+DOnjvFTnzP8+wDIM3DuMjPUePM53sZM8MYo4fQ
MP238szEB1DQBh3TMCnL28wf+XFkRexseHZx8jggrTIgbiSPq8u7MOzRPTDFAMDUUxyI8uzE/1G9
wzSM0pp4wxHw0zawwDj91SoKAIWcxTUtdRGTObhyzRVAcMnMkf0xGXAd1I+KdUfc0pthsXncGgby
ynajQw/jZt+c0fhM0vC8vhrtASINuYgsKiWNNhiNwxhw1Vid1Wkgy0exzWCd2eQJxUyswWVt1nED
PgBTNRHANJFGOQ+Q2pWD2qqtFNvbPl5i1lHHL10yMJTTZKndJer7PAq9Hwnsxq4NVQ1BQ5gDIVZi
3D8MJe58bab7yE2NvKur0b5cyR4QzA0y3Tkc2ZOdi9dm2blB25od3n2JxZuruTbNNBxgKzYdN+4T
dcBAH2bNAQgCMVIXJhCjM6mRKlriQ5cRMf97LHVI8wCa5gOpkbdLESccstWdgdSz8gC1k8dPMjsF
VcGYEWCzk86/vM63u7kinbstrNEiXcli7dztXMj5bMmSvd1SA4ixBAPHcxtL1DMxYODiXeOkgwED
zcLmLdsBACUIg85o48Y2REHQ2GhpEzChsTk+MzaSlt4vGACunRq78WsE53CcIOCm5wFSDoYILjTv
NMcI4OC7vUZzHI1JTNQQUg6rbCtKrR8hXt0DrcWNLdgj/dyoW8Z/CwApruIrnsAEYCEbEDGLsRi/
YOOGLs1xvuHnHXU+bkPvUzMIQ3BDjjAQYL8YgC8CbgD2K34o2OP/EiYVED630jO2suU9M0H/pR0A
D9DkPT00NE7genwwbjyN6wi4Q43UgYsb56fH2C3Qdy7SiZ67hU3Yg03siYyV7Lu7oLy7Hd2Re87n
UZNBPXNHcWIqzQYDVXPo2p4GOD7QmosBNu0zQtTeBrAAEaMUUh7pRB4ZFGwlWC4qoc4J6h7vsxQA
pR4A3gMDeZYaoyfjMZ7tdFLE7PNPRZwqMYAfPG3RBYTt7oMUoQLm62vdh4y8zY26uuvCgoy7UXzM
nE3FFe/FMfnh0jvy0pu7eL4UJ50xDLXyDOWHoVNHMHBHSEGFhb7tNt/BcX4AjUPfUtfoVsLvAs4B
5E7kSzUnWO4qNmQ35w4APWMqPaMUsbTq/1nHhj2e6nqEG6oOhpyDFAv+C61cJZwRAwhA3ET8C3SI
7cAOwxzN2fm8yGPdyFp83YfdkaxL8nZP8tTdj8++MUdxAVj927NTA03TNEZ884bvAWMdxQgj4/mN
Rio45KX36ENP6bcyzGs0abMCdebX6WDfM40x5B7Q9PvR9JJWDsO85WDI1W58N9BwN+RgILJc60Us
H1ufFJx9AHL/yOy8FGyPxWTdIFNN93c//CN/4mmw93zvDMIkxsDGEs7g/Nxz+DfP2dS8hL/DCaiR
NAFwAU8eMU70PsDw40+lKu9+cZHxVJpGabJdJbZSMKaR35ef5aiv9aiiRwN/GY271ldPcP/WDgKG
gQCeIkJlBY1AMzVH6dFYcx93s9C9t+h4hwmReMjtfMAbxud8emzFKbUKa0Idgi23y71wwuJxwstN
oNPqsjlc6HQK4/E7HiZA8/o9v+//AwYKDhLqAQwgJh5AECgQQCAQIBgo9EAEGNBcBkBoYpoEhIpy
RDwEEMwAhFb4EAQg1FRUcAQoVET4YLiKnj54mJLSALiyFhofIyfzvUxdEFxcWFE15FGYXRPMjRFc
CyRkg3OEX1yHMcB1MGjXpd8pv8PHy8//HSQiHiDwimb2RCj4oqEAAZYHAGnIUmDLFgAAB2n8K+bv
YQ9ZeiogyKgACwCLFSvMoCdyJLIFVQj/gKsSjQoPJ1q6dUmgbQy5axtozeSwARuHc+gKFGAAFF27
MP1IIk2qNKk9Rfr2GQi5dCrVqlOZFXGGksCUO+KmUHNiDSaXmzl1dgMjJsBaDmy8qGVHlKgcMZ2s
4s2r98kQfJtCcUixdzDhwntMUkEpjmsRA9BWTmnZg2wXtTnfesmWk9s1mWHmztUW0DDp0vAiDMl3
B8Jo065fKx1yEpo0Kwd8vKQswLI2AphjJtiwJg1My0J/1p1zFzbz5n1KAIgQQarz6tYLYa2tvUhY
GmMpy2TLFictzrrPc9F8dhv16+7fw48vvwfWDfa3E7G/gbsP9AkuOPYMNM8QsBN6B36zC54YqMzX
oIMP0hACADs=


--=felis-related=20030526080720=28783--
