Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 05:26:56 +0400
X-Deliver-To: lavrushin@iph.ru
Received: from tofsla.infosys.ru ([213.138.192.178] verified)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP id 187646722 for lavrushin@iph.ru; Mon, 26 May 2003 05:30:11 +0400
Received: from localhost (tty15.infosys.ru [213.138.192.46])
	by tofsla.infosys.ru (8.12.9/8.12.9) with SMTP id h4Q1Tnv8028506
	for <lavrushin@iph.ru>; Mon, 26 May 2003 12:29:50 +1100
Received: from boss ([192.168.255.7]) by local with ESMTP id 257 for <lavrushin@iph.ru>; Mon, 26 May 2003 12:28:05 +1100
X-Mail-Server: Eserv/2.99/ннн кНЦХЙЮ
Date: Mon, 26 May 2003 12:24:11 +1100
From: =?koi8-r?B?8/TzIO7ByM/Ey8E=?= <stsnak@stslogistics.com>
X-Mailer: The Bat! (v1.53d)
Reply-To: =?koi8-r?B?8/TzIO7ByM/Ey8E=?= <stsnak@stslogistics.com>
X-Priority: 3 (Normal)
Message-ID: <18415548137.20030526122411@stslogistics.com>
To: Lavrushin Andrey <lavrushin@iph.ru>
Subject: (Archive Copy) Re[2]:
In-Reply-To: <000801c32113$672db5d0$a4180e0a@iph.int>
References: <000801c32113$672db5d0$a4180e0a@iph.int>
MIME-Version: 1.0
Content-Type: text/plain; charset=koi8-r
Content-Transfer-Encoding: 8bit
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru


Андрей,мне нужны размеры,чтобы я написал
заявку в "Трансфес" без этих данных письмо
будет неполное и его не примут к рассмотрению.

B.RGDS.
Руслан.
"STS-Logistics"Nakhodka,Russia
Tel: +7(4236)692-568
Fax: +7(4236)679-734
mailto:stsnak@stslogistics.com
WWW.STSLOGISTICS.COM

 Lavrushin.

Вы писали 23 мая 2003 г., 21:09:30:

 LA> Руслан привет!!!!!!!!!!!
LA> Расклад такой:
LA> Д375 - 2 места (бульдозер 59 тонн, 148 куб.м. + отвал 20F контейнер)
LA> Д65 - 1 место (22 тонны, 60 куб.м.)
LA> Спасибо за содействие,
LA> Лавр.

LA> -----Original Message-----
LA> From: СТС Находка [mailto:stsnak@stslogistics.com]
LA> Sent: Friday, May 23, 2003 6:00 AM
LA> To: Lavrushin Andrey
LA> Subject: Re:



LA> Андрей,дай размеры и вес данной техники.
LA> В случае,если она разобрана,дай размеры
LA> и вес каждого места.Я переговорил с представитеялми
LA> "Трансфес",они готовы пролобировать этот вопрос
LA> с ДВМП для отправки данной техники на контейнеровозе.
LA> Такая возможность есть надо только продавить.

LA> B.RGDS.
LA> Руслан.
LA> "STS-Logistics"Nakhodka,Russia
LA> Tel: +7(4236)692-568
LA> Fax: +7(4236)679-734
LA> mailto:stsnak@stslogistics.com
LA> WWW.STSLOGISTICS.COM

LA>  Lavrushin.

LA> Вы писали 22 мая 2003 г., 20:30:56:

LA>  LA> Руслан привет!!!!!!!!!!!
LA>> У меня возникла проблема с отправкой Д373 и Д65 из Восточного в Магадан.
LA>> Срок подхода груза в Восточный ориентировочно 15 июня.
LA>> Сможешь помочь???????????
LA>> Лавр.

