Return-Path: <postmaster@iph.ru>
Received: from iph.ru [10.14.24.3] by iph.ru [10.14.24.3]
	with RAW (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 03:00:40 +0400
Date: Mon, 26 May 2003 03:00:40 +0400
From: postmaster@iph.ru
Reply-To: postmaster@iph.ru
Subject: (Archive Copy) MDaemon Notification -- AV Updated Mon 2003-05-26 03:00:24
To: postmaster@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru
Message-ID: <MDAEMON280028200305260300.AA0040094@iph.ru>
Mime-Version: 1.0
X-Actual-From: postmaster@iph.ru
Content-Type: text/plain; charset=US-ASCII

An update to the virus definition database has been performed.  For complete information on this update visit:

http://avupdates.deerfield.com/pub/dkavarchive/

