Received: from mail.iph.ru [195.2.72.152] by iph.ru [10.14.24.3]
	with DomainPOP (MDaemon.PRO.v5.0.5.R)
	for <arc@iph.ru>; Mon, 26 May 2003 01:12:22 +0400
X-Deliver-To: lavrushin@iph.ru
Received: from alpha.sferacom.ru ([213.24.91.246] verified)
  by frontend1.aha.ru (CommuniGate Pro SMTP 4.0.6)
  with ESMTP-TLS id 187616788 for lavrushin@iph.ru; Mon, 26 May 2003 01:15:05 +0400
Received: from sonya (fw-1.pne.magadan.ru [213.24.242.99])
	by alpha.sferacom.ru (8.11.6/8.11.3) with SMTP id h4PLEXV34220
	for <lavrushin@iph.ru>; Mon, 26 May 2003 09:14:38 +1200 (MAGST)
	(envelope-from pne@sferacom.ru)
Message-ID: <002301c3230b$554cba10$7600a8c0@sonya>
Reply-To: "Sh. Sonia" <pne@sferacom.ru>
From: "Sh. Sonia" <pne@sferacom.ru>
To: <lavrushin@iph.ru>
References: <000201c32106$ee9b6e70$a4180e0a@iph.int>
Subject: (Archive Copy) Re:
Date: Mon, 26 May 2003 09:16:01 +1100
Organization: PNE
MIME-Version: 1.0
Content-Type: text/plain;
	charset="koi8-r"
Content-Transfer-Encoding: 8bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2919.6700
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2919.6700
X-MDArchive-Copy: 1
X-MDRemoteIP: 195.2.72.152
X-MDRcpt-To: arc@iph.ru
X-MDaemon-Deliver-To: arc@iph.ru

Привет Андрей

Дан уехал в командировку
Приеде через несколько дней

Sonya
Pacific North Equipment (Magadan), Inc.
----- Original Message -----
From: "Lavrushin Andrey" <lavrushin@iph.ru>
To: "pne (Эл. почта)" <pne@sferacom.ru>
Sent: Friday, May 23, 2003 7:40 PM


> Дан привет!!!!!!!!!!
> Дай размеры и вес техники.
> В случае,если она разобрана,дай размеры
> и вес каждого места.Я переговорил с представитеялми
> "Трансфес",они готовы пролобировать этот вопрос
> с ДВМП для отправки данной техники на контейнеровозе.
> Такая возможность есть надо только продавить.
> Лавр.
>
>

